### ISSUE TITLE
Firebase deploy HTTP 500 error internal error encountered

### ISSUE THREAD

**Issue by nafroman** [firebase/firebase-tools#1609]
CLI Version: 7.2.3
Platform: win32
Node Version: v8.11.4

Error when updating website

```
[debug] [2019-08-19T20:02:31.501Z] ----------------------------------------------------------------------
[debug] [2019-08-19T20:02:31.506Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\nath_\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2019-08-19T20:02:31.506Z] CLI Version:   7.2.3
[debug] [2019-08-19T20:02:31.506Z] Platform:      win32
[debug] [2019-08-19T20:02:31.506Z] Node Version:  v8.11.4
[debug] [2019-08-19T20:02:31.507Z] Time:          Mon Aug 19 2019 21:02:31 GMT+0100 (GMT Summer Time)
[debug] [2019-08-19T20:02:31.507Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-08-19T20:02:31.517Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-08-19T20:02:31.519Z] > authorizing via signed-in user
[debug] [2019-08-19T20:02:31.519Z] [iam] checking project humphrey-stretton for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]
[debug] [2019-08-19T20:02:31.520Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/humphrey-stretton:testIamPermissions  

[debug] [2019-08-19T20:02:32.737Z] <<< HTTP RESPONSE 200
[debug] [2019-08-19T20:02:32.741Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/humphrey-stretton  
 
[debug] [2019-08-19T20:02:33.040Z] <<< HTTP RESPONSE 200
[warn] !  functions: package.json indicates an outdated version of firebase-functions.
 Please upgrade using npm install --save firebase-functions@latest in your functions directory.
[info] 
[info] === Deploying to 'humphrey-stretton'...
[info] 
[info] i  deploying functions, hosting
[debug] [2019-08-19T20:02:34.957Z] > [functions] package.json contents: {
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "firebase-admin": "~7.0.0",
    "firebase-functions": "^2.2.0"
  },
  "private": true,
  "engines": {
    "node": "8"
  }
}
[info] i  functions: ensuring necessary APIs are enabled...
[debug] [2019-08-19T20:02:34.960Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/humphrey-stretton/services/cloudfunctions.googleapis.com  
 
[debug] [2019-08-19T20:02:34.962Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/humphrey-stretton/services/runtimeconfig.googleapis.com  
 
[debug] [2019-08-19T20:02:35.911Z] <<< HTTP RESPONSE 200
[debug] [2019-08-19T20:02:35.942Z] <<< HTTP RESPONSE 200
[info] +  functions: all necessary APIs are enabled
[debug] [2019-08-19T20:02:35.946Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/humphrey-stretton/adminSdkConfig  
 
[debug] [2019-08-19T20:02:36.189Z] <<< HTTP RESPONSE 200
[debug] [2019-08-19T20:02:36.189Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/humphrey-stretton/versions  

[debug] [2019-08-19T20:02:37.587Z] <<< HTTP RESPONSE 200
[info] i  functions: preparing functions directory for uploading...
[debug] [2019-08-19T20:02:37.591Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/humphrey-stretton/configs  
 
[debug] [2019-08-19T20:02:37.955Z] <<< HTTP RESPONSE 200
[info] i  hosting[humphrey-stretton]: beginning deploy...
[info] i  hosting[humphrey-stretton]: found 49 files in ./dist
[debug] [2019-08-19T20:02:38.247Z] [hosting] hash cache [ZGlzdA] load error: lines is not defined
[debug] [2019-08-19T20:02:39.418Z] [hosting] hash cache [ZGlzdA] stored for 49 files
[debug] [2019-08-19T20:02:39.418Z] [hosting][hash queue][FINAL]
[debug] [2019-08-19T20:02:39.418Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/humphrey-stretton/versions/58d5b600938d6162:populateFiles  
 <request body omitted>
[debug] [2019-08-19T20:02:41.231Z] <<< HTTP RESPONSE 200
[debug] [2019-08-19T20:02:41.232Z] [hosting][populate queue][FINAL]
[debug] [2019-08-19T20:02:41.232Z] [hosting] uploads queued: 0
[debug] [2019-08-19T20:02:41.232Z] [hosting][upload queue][FINAL]
[info] +  hosting[humphrey-stretton]: file upload complete
[debug] [2019-08-19T20:02:41.233Z] [hosting] deploy completed after 3024ms
[debug] [2019-08-19T20:02:41.234Z] >>> HTTP REQUEST GET https://cloudfunctions.googleapis.com/v1/projects/humphrey-stretton/locations/-/functions  
 
[debug] [2019-08-19T20:02:41.847Z] <<< HTTP RESPONSE 200
[debug] [2019-08-19T20:02:41.848Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/humphrey-stretton/services/cloudscheduler.googleapis.com  
 
[debug] [2019-08-19T20:02:42.768Z] <<< HTTP RESPONSE 200
[debug] [2019-08-19T20:02:42.770Z] [
  {
    "config": {
      "public": "./dist",
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ],
      "site": "humphrey-stretton"
    },
    "site": "humphrey-stretton",
    "version": "sites/humphrey-stretton/versions/58d5b600938d6162"
  }
]
[info] i  hosting[humphrey-stretton]: finalizing version...
[debug] [2019-08-19T20:02:42.772Z] >>> HTTP REQUEST PATCH https://firebasehosting.googleapis.com/v1beta1/sites/humphrey-stretton/versions/58d5b600938d6162?updateMask=status  

[debug] [2019-08-19T20:02:43.691Z] <<< HTTP RESPONSE 500
[debug] [2019-08-19T20:02:43.691Z] <<< HTTP RESPONSE BODY
[error] 
[error] Error: HTTP Error: 500, Internal error encountered.
[debug] [2019-08-19T20:02:43.697Z] Error Context: {
  "body": {
    "error": {
      "code": 500,
      "message": "Internal error encountered.",
      "status": "INTERNAL"
    }
  },
  "response": {
    "statusCode": 500,
    "body": {
      "error": {
        "code": 500,
        "message": "Internal error encountered.",
        "status": "INTERNAL"
      }
    },
    "headers": {
      "vary": "X-Origin, Referer, Origin,Accept-Encoding",
      "content-type": "application/json; charset=UTF-8",
      "date": "Mon, 19 Aug 2019 20:02:37 GMT",
      "server": "ESF",
      "cache-control": "private",
      "x-xss-protection": "0",
      "x-frame-options": "SAMEORIGIN",
      "x-content-type-options": "nosniff",
      "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,43,39\"",
      "accept-ranges": "none",
      "transfer-encoding": "chunked"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "firebasehosting.googleapis.com",
        "port": 443,
        "hostname": "firebasehosting.googleapis.com",
        "hash": null,
        "search": "?updateMask=status",
        "query": "updateMask=status",
        "pathname": "/v1beta1/sites/humphrey-stretton/versions/58d5b600938d6162",
        "path": "/v1beta1/sites/humphrey-stretton/versions/58d5b600938d6162?updateMask=status",
        "href": "https://firebasehosting.googleapis.com/v1beta1/sites/humphrey-stretton/versions/58d5b600938d6162?updateMask=status"
      },
      "method": "PATCH"
    }
  }
}
[debug] [2019-08-19T20:03:31.159Z] ----------------------------------------------------------------------
[debug] [2019-08-19T20:03:31.163Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\nath_\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js deploy
[debug] [2019-08-19T20:03:31.163Z] CLI Version:   7.2.3
[debug] [2019-08-19T20:03:31.163Z] Platform:      win32
[debug] [2019-08-19T20:03:31.163Z] Node Version:  v8.11.4
[debug] [2019-08-19T20:03:31.164Z] Time:          Mon Aug 19 2019 21:03:31 GMT+0100 (GMT Summer Time)
[debug] [2019-08-19T20:03:31.164Z] ----------------------------------------------------------------------
[debug] 
[debug] [2019-08-19T20:03:31.176Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2019-08-19T20:03:31.178Z] > authorizing via signed-in user
[debug] [2019-08-19T20:03:31.178Z] [iam] checking project humphrey-stretton for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]
[debug] [2019-08-19T20:03:31.179Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/humphrey-stretton:testIamPermissions  

[debug] [2019-08-19T20:03:31.753Z] <<< HTTP RESPONSE 200
[debug] [2019-08-19T20:03:31.756Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/humphrey-stretton  
 
[debug] [2019-08-19T20:03:32.311Z] <<< HTTP RESPONSE 200
[warn] !  functions: package.json indicates an outdated version of firebase-functions.
 Please upgrade using npm install --save firebase-functions@latest in your functions directory.
[info] 
[info] === Deploying to 'humphrey-stretton'...
[info] 
[info] i  deploying functions, hosting
[debug] [2019-08-19T20:03:35.057Z] > [functions] package.json contents: {
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "firebase-admin": "~7.0.0",
    "firebase-functions": "^2.2.0"
  },
  "private": true,
  "engines": {
    "node": "8"
  }
}
[info] i  functions: ensuring necessary APIs are enabled...
[debug] [2019-08-19T20:03:35.060Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/humphrey-stretton/services/cloudfunctions.googleapis.com  
 
[debug] [2019-08-19T20:03:35.061Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/humphrey-stretton/services/runtimeconfig.googleapis.com  
 
[debug] [2019-08-19T20:03:36.331Z] <<< HTTP RESPONSE 200
[debug] [2019-08-19T20:03:36.395Z] <<< HTTP RESPONSE 200
[info] +  functions: all necessary APIs are enabled
[debug] [2019-08-19T20:03:36.397Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/humphrey-stretton/adminSdkConfig  
 
[debug] [2019-08-19T20:03:36.893Z] <<< HTTP RESPONSE 200
[debug] [2019-08-19T20:03:36.894Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/humphrey-stretton/versions  

[debug] [2019-08-19T20:03:38.838Z] <<< HTTP RESPONSE 200
[info] i  functions: preparing functions directory for uploading...
[debug] [2019-08-19T20:03:38.842Z] >>> HTTP REQUEST GET https://runtimeconfig.googleapis.com/v1beta1/projects/humphrey-stretton/configs  
 
[debug] [2019-08-19T20:03:40.063Z] <<< HTTP RESPONSE 200
[info] i  hosting[humphrey-stretton]: beginning deploy...
[info] i  hosting[humphrey-stretton]: found 49 files in ./dist
[debug] [2019-08-19T20:03:40.348Z] [hosting] hash cache [ZGlzdA] load error: lines is not defined
[debug] [2019-08-19T20:03:41.655Z] [hosting] hash cache [ZGlzdA] stored for 49 files
[debug] [2019-08-19T20:03:41.657Z] [hosting][hash queue][FINAL]
[debug] [2019-08-19T20:03:41.657Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/humphrey-stretton/versions/3132ad5d71caec6a:populateFiles  
 <request body omitted>
[debug] [2019-08-19T20:03:43.448Z] <<< HTTP RESPONSE 200
[debug] [2019-08-19T20:03:43.448Z] [hosting][populate queue][FINAL]
[debug] [2019-08-19T20:03:43.448Z] [hosting] uploads queued: 0
[debug] [2019-08-19T20:03:43.448Z] [hosting][upload queue][FINAL]
[info] +  hosting[humphrey-stretton]: file upload complete
[debug] [2019-08-19T20:03:43.450Z] [hosting] deploy completed after 3129ms
[debug] [2019-08-19T20:03:43.452Z] >>> HTTP REQUEST GET https://cloudfunctions.googleapis.com/v1/projects/humphrey-stretton/locations/-/functions  
 
[debug] [2019-08-19T20:03:44.390Z] <<< HTTP RESPONSE 200
[debug] [2019-08-19T20:03:44.395Z] >>> HTTP REQUEST GET https://serviceusage.googleapis.com/v1/projects/humphrey-stretton/services/cloudscheduler.googleapis.com  
 
[debug] [2019-08-19T20:03:45.371Z] <<< HTTP RESPONSE 200
[debug] [2019-08-19T20:03:45.373Z] [
  {
    "config": {
      "public": "./dist",
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ],
      "site": "humphrey-stretton"
    },
    "site": "humphrey-stretton",
    "version": "sites/humphrey-stretton/versions/3132ad5d71caec6a"
  }
]
[info] i  hosting[humphrey-stretton]: finalizing version...
[debug] [2019-08-19T20:03:45.376Z] >>> HTTP REQUEST PATCH https://firebasehosting.googleapis.com/v1beta1/sites/humphrey-stretton/versions/3132ad5d71caec6a?updateMask=status  

[debug] [2019-08-19T20:03:46.564Z] <<< HTTP RESPONSE 200
[debug] [2019-08-19T20:03:46.565Z] [hosting] finalized version for humphrey-stretton:
[info] +  hosting[humphrey-stretton]: version finalized
[info] i  hosting[humphrey-stretton]: releasing new version...
[debug] [2019-08-19T20:03:46.571Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/humphrey-stretton/releases?version_name=sites/humphrey-stretton/versions/3132ad5d71caec6a  

[debug] [2019-08-19T20:03:47.542Z] <<< HTTP RESPONSE 500
[debug] [2019-08-19T20:03:47.542Z] <<< HTTP RESPONSE BODY
[error] 
[error] Error: HTTP Error: 500, Internal error encountered.
[debug] [2019-08-19T20:03:47.552Z] Error Context: {
  "body": {
    "error": {
      "code": 500,
      "message": "Internal error encountered.",
      "status": "INTERNAL"
    }
  },
  "response": {
    "statusCode": 500,
    "body": {
      "error": {
        "code": 500,
        "message": "Internal error encountered.",
        "status": "INTERNAL"
      }
    },
    "headers": {
      "vary": "X-Origin, Referer, Origin,Accept-Encoding",
      "content-type": "application/json; charset=UTF-8",
      "date": "Mon, 19 Aug 2019 20:03:41 GMT",
      "server": "ESF",
      "cache-control": "private",
      "x-xss-protection": "0",
      "x-frame-options": "SAMEORIGIN",
      "x-content-type-options": "nosniff",
      "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,43,39\"",
      "accept-ranges": "none",
      "transfer-encoding": "chunked"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "firebasehosting.googleapis.com",
        "port": 443,
        "hostname": "firebasehosting.googleapis.com",
        "hash": null,
        "search": "?version_name=sites/humphrey-stretton/versions/3132ad5d71caec6a",
        "query": "version_name=sites/humphrey-stretton/versions/3132ad5d71caec6a",
        "pathname": "/v1beta1/sites/humphrey-stretton/releases",
        "path": "/v1beta1/sites/humphrey-stretton/releases?version_name=sites/humphrey-stretton/versions/3132ad5d71caec6a",
        "href": "https://firebasehosting.googleapis.com/v1beta1/sites/humphrey-stretton/releases?version_name=sites/humphrey-stretton/versions/3132ad5d71caec6a"
      },
      "method": "POST"
    }
  }
}
```

**Comment by bkendall** [comment]
This falls solidly into "what's up, Hosting?" territory. There are two different errors here, for what it's worth - both deploy commands failing at different spots.

**Comment by Nemutagk** [comment]
I have a similar problem, if not the same, we try to deploy the project from BitBucket to Firebase through the Pipeline and this is what the console throws:

`+ firebase deploy --token=$FIREBASE_TOKEN --non-interactive --debug
[2019-08-19T20:24:17.438Z] ----------------------------------------------------------------------
[2019-08-19T20:24:17.440Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy --token=__TOKEN__ --non-interactive --debug
[2019-08-19T20:24:17.441Z] CLI Version:   7.2.3
[2019-08-19T20:24:17.441Z] Platform:      linux
[2019-08-19T20:24:17.441Z] Node Version:  v8.12.0
[2019-08-19T20:24:17.441Z] Time:          Mon Aug 19 2019 20:24:17 GMT+0000 (UTC)
[2019-08-19T20:24:17.441Z] ----------------------------------------------------------------------
[2019-08-19T20:24:17.450Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-08-19T20:24:17.450Z] > authorizing via --token option
[2019-08-19T20:24:17.451Z] [iam] checking project __PROYECTO__ for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[2019-08-19T20:24:17.451Z] > refreshing access token with scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-08-19T20:24:17.452Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[2019-08-19T20:24:17.535Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=utf-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 19 Aug 2019 20:24:17 GMT, server=scaffolding on HTTPServer2, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:17.536Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/__PROYECTO__:testIamPermissions  
 permissions=[firebase.projects.get, firebasehosting.sites.update]
[2019-08-19T20:24:17.603Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 19 Aug 2019 20:24:17 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=46, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:17.605Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/__PROYECTO__  
 
[2019-08-19T20:24:17.810Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 19 Aug 2019 20:24:17 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
=== Deploying to '__PROYECTO__'...
i  deploying hosting
[2019-08-19T20:24:17.813Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions  
 rewrites=[glob=**, path=/index.html], deployment-tool=cli-firebase
[2019-08-19T20:24:18.630Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 19 Aug 2019 20:24:18 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
i  hosting[__PROYECTO__]: beginning deploy...
i  hosting[__PROYECTO__]: found 45 files in dist
[2019-08-19T20:24:18.645Z] [hosting] hash cache [ZGlzdA] load error: lines is not defined
[2019-08-19T20:24:19.209Z] [hosting] hash cache [ZGlzdA] stored for 45 files
[2019-08-19T20:24:19.210Z] [hosting][hash queue][FINAL] max=551, min=23, avg=51.46666666666667, active=0, complete=45, success=45, errored=0, retried=0, total=45, elapsed=564
[2019-08-19T20:24:19.210Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c:populateFiles  
 <request body omitted>
[2019-08-19T20:24:19.384Z] <<< HTTP RESPONSE 500 vary=X-Origin, Referer, Origin,Accept-Encoding, content-type=application/json; charset=UTF-8, date=Mon, 19 Aug 2019 20:24:19 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:19.385Z] <<< HTTP RESPONSE BODY code=500, message=Internal error encountered., status=INTERNAL
[2019-08-19T20:24:19.787Z] [populateQueue] Retrying task index 0
[2019-08-19T20:24:19.787Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c:populateFiles  
 <request body omitted>
i  hosting: adding files to version [0/45] (0%)
[2019-08-19T20:24:20.920Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 19 Aug 2019 20:24:20 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:20.924Z] [hosting][populate queue][FINAL] max=1137, min=1137, avg=1137, active=0, complete=1, success=1, errored=0, retried=1, total=1, elapsed=1716
[2019-08-19T20:24:20.924Z] [hosting] uploads queued: 7
[2019-08-19T20:24:22.540Z] [hosting][upload queue][FINAL] max=1620, min=1176, avg=1278.4285714285713, active=0, complete=7, success=7, errored=0, retried=0, total=7, elapsed=1620
✔  hosting[__PROYECTO__]: file upload complete
[2019-08-19T20:24:22.541Z] [hosting] deploy completed after 3910ms
[2019-08-19T20:24:22.542Z] [
  {
    "config": {
      "public": "dist",
      "ignore": [
        "firebase.json",
        "**/.*",
        "**/node_modules/**"
      ],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ],
      "site": "__PROYECTO__"
    },
    "site": "__PROYECTO__",
    "version": "sites/__PROYECTO__/versions/4a616a04137b499c"
  }
]
i  hosting[__PROYECTO__]: finalizing version...
[2019-08-19T20:24:22.542Z] >>> HTTP REQUEST PATCH https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c?updateMask=status  
 status=FINALIZED
[2019-08-19T20:24:22.708Z] <<< HTTP RESPONSE 500 vary=X-Origin, Referer, Origin,Accept-Encoding, content-type=application/json; charset=UTF-8, date=Mon, 19 Aug 2019 20:24:22 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:22.708Z] <<< HTTP RESPONSE BODY code=500, message=Internal error encountered., status=INTERNAL
Error: HTTP Error: 500, Internal error encountered.
[2019-08-19T20:24:22.710Z] Error Context: {
i  hosting[__PROYECTO__]: found 45 files in dist
[2019-08-19T20:24:18.645Z] [hosting] hash cache [ZGlzdA] load error: lines is not defined
[2019-08-19T20:24:19.209Z] [hosting] hash cache [ZGlzdA] stored for 45 files
[2019-08-19T20:24:19.210Z] [hosting][hash queue][FINAL] max=551, min=23, avg=51.46666666666667, active=0, complete=45, success=45, errored=0, retried=0, total=45, elapsed=564
[2019-08-19T20:24:19.210Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c:populateFiles  
 <request body omitted>
[2019-08-19T20:24:19.384Z] <<< HTTP RESPONSE 500 vary=X-Origin, Referer, Origin,Accept-Encoding, content-type=application/json; charset=UTF-8, date=Mon, 19 Aug 2019 20:24:19 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:19.385Z] <<< HTTP RESPONSE BODY code=500, message=Internal error encountered., status=INTERNAL
[2019-08-19T20:24:19.787Z] [populateQueue] Retrying task index 0
[2019-08-19T20:24:19.787Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c:populateFiles  
 <request body omitted>
i  hosting: adding files to version [0/45] (0%)
[2019-08-19T20:24:20.920Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 19 Aug 2019 20:24:20 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:20.924Z] [hosting][populate queue][FINAL] max=1137, min=1137, avg=1137, active=0, complete=1, success=1, errored=0, retried=1, total=1, elapsed=1716
[2019-08-19T20:24:20.924Z] [hosting] uploads queued: 7
[2019-08-19T20:24:22.540Z] [hosting][upload queue][FINAL] max=1620, min=1176, avg=1278.4285714285713, active=0, complete=7, success=7, errored=0, retried=0, total=7, elapsed=1620
✔  hosting[__PROYECTO__]: file upload complete
[2019-08-19T20:24:22.541Z] [hosting] deploy completed after 3910ms
[2019-08-19T20:24:22.542Z] [
  {
    "config": {
      "public": "dist",
      "ignore": [
        "firebase.json",
        "**/.*",
        "**/node_modules/**"
      ],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ],
      "site": "__PROYECTO__"
    },
    "site": "__PROYECTO__",
    "version": "sites/__PROYECTO__/versions/4a616a04137b499c"
  }
]
i  hosting[__PROYECTO__]: finalizing version...
[2019-08-19T20:24:22.542Z] >>> HTTP REQUEST PATCH https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c?updateMask=status  
 status=FINALIZED
[2019-08-19T20:24:22.708Z] <<< HTTP RESPONSE 500 vary=X-Origin, Referer, Origin,Accept-Encoding, content-type=application/json; charset=UTF-8, date=Mon, 19 Aug 2019 20:24:22 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:22.708Z] <<< HTTP RESPONSE BODY code=500, message=Internal error encountered., status=INTERNAL
Error: HTTP Error: 500, Internal error encountered.
[2019-08-19T20:24:22.710Z] Error Context: {
  "body": {
    "error": {
      "code": 500,
      "message": "Internal error encountered.",
      "status": "INTERNAL"
    }
  },
  "response": {
    "statusCode": 500,
    "body": {
      "error": {
        "code": 500,
        "message": "Internal error encountered.",
        "status": "INTERNAL"
      }
    },
    "headers": {
      "vary": "X-Origin, Referer, Origin,Accept-Encoding",
      "content-type": "application/json; charset=UTF-8",
      "date": "Mon, 19 Aug 2019 20:24:22 GMT",
      "server": "ESF",
      "cache-control": "private",
      "x-xss-protection": "0",
      "x-frame-options": "SAMEORIGIN",
      "x-content-type-options": "nosniff",
      "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,43,39\"",
      "accept-ranges": "none",
      "transfer-encoding": "chunked"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "firebasehosting.googleapis.com",
        "port": 443,
        "hostname": "firebasehosting.googleapis.com",
        "hash": null,
        "search": "?updateMask=status",
        "query": "updateMask=status",
        "pathname": "/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c",
        "path": "/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c?updateMask=status",
        "href": "https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c?updateMask=status"
      },
      "method": "PATCH"
    }
  }
}`

**Comment by bkendall** [comment]
We're aware of these issues occurring and the team is actively working on it. Sorry for the inconvenience, but hang on with us while we work this out...

**Comment by Nemutagk** [comment]
I have a similar problem, if not the same, we try to deploy the project from BitBucket to Firebase through the Pipeline and this is what the console throws:

```
+ firebase deploy --token=$FIREBASE_TOKEN --non-interactive --debug
[2019-08-19T20:24:17.438Z] ----------------------------------------------------------------------
[2019-08-19T20:24:17.440Z] Command:       /usr/local/bin/node /usr/local/bin/firebase deploy --token=__TOKEN__ --non-interactive --debug
[2019-08-19T20:24:17.441Z] CLI Version:   7.2.3
[2019-08-19T20:24:17.441Z] Platform:      linux
[2019-08-19T20:24:17.441Z] Node Version:  v8.12.0
[2019-08-19T20:24:17.441Z] Time:          Mon Aug 19 2019 20:24:17 GMT+0000 (UTC)
[2019-08-19T20:24:17.441Z] ----------------------------------------------------------------------
[2019-08-19T20:24:17.450Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-08-19T20:24:17.450Z] > authorizing via --token option
[2019-08-19T20:24:17.451Z] [iam] checking project __PROYECTO__ for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[2019-08-19T20:24:17.451Z] > refreshing access token with scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2019-08-19T20:24:17.452Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[2019-08-19T20:24:17.535Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=utf-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 19 Aug 2019 20:24:17 GMT, server=scaffolding on HTTPServer2, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:17.536Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/__PROYECTO__:testIamPermissions  
 permissions=[firebase.projects.get, firebasehosting.sites.update]
[2019-08-19T20:24:17.603Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 19 Aug 2019 20:24:17 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, server-timing=gfet4t7; dur=46, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:17.605Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/__PROYECTO__  
 
[2019-08-19T20:24:17.810Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 19 Aug 2019 20:24:17 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
=== Deploying to '__PROYECTO__'...
i  deploying hosting
[2019-08-19T20:24:17.813Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions  
 rewrites=[glob=**, path=/index.html], deployment-tool=cli-firebase
[2019-08-19T20:24:18.630Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 19 Aug 2019 20:24:18 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
i  hosting[__PROYECTO__]: beginning deploy...
i  hosting[__PROYECTO__]: found 45 files in dist
[2019-08-19T20:24:18.645Z] [hosting] hash cache [ZGlzdA] load error: lines is not defined
[2019-08-19T20:24:19.209Z] [hosting] hash cache [ZGlzdA] stored for 45 files
[2019-08-19T20:24:19.210Z] [hosting][hash queue][FINAL] max=551, min=23, avg=51.46666666666667, active=0, complete=45, success=45, errored=0, retried=0, total=45, elapsed=564
[2019-08-19T20:24:19.210Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c:populateFiles  
 <request body omitted>
[2019-08-19T20:24:19.384Z] <<< HTTP RESPONSE 500 vary=X-Origin, Referer, Origin,Accept-Encoding, content-type=application/json; charset=UTF-8, date=Mon, 19 Aug 2019 20:24:19 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:19.385Z] <<< HTTP RESPONSE BODY code=500, message=Internal error encountered., status=INTERNAL
[2019-08-19T20:24:19.787Z] [populateQueue] Retrying task index 0
[2019-08-19T20:24:19.787Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c:populateFiles  
 <request body omitted>
i  hosting: adding files to version [0/45] (0%)
[2019-08-19T20:24:20.920Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 19 Aug 2019 20:24:20 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:20.924Z] [hosting][populate queue][FINAL] max=1137, min=1137, avg=1137, active=0, complete=1, success=1, errored=0, retried=1, total=1, elapsed=1716
[2019-08-19T20:24:20.924Z] [hosting] uploads queued: 7
[2019-08-19T20:24:22.540Z] [hosting][upload queue][FINAL] max=1620, min=1176, avg=1278.4285714285713, active=0, complete=7, success=7, errored=0, retried=0, total=7, elapsed=1620
✔  hosting[__PROYECTO__]: file upload complete
[2019-08-19T20:24:22.541Z] [hosting] deploy completed after 3910ms
[2019-08-19T20:24:22.542Z] [
  {
    "config": {
      "public": "dist",
      "ignore": [
        "firebase.json",
        "**/.*",
        "**/node_modules/**"
      ],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ],
      "site": "__PROYECTO__"
    },
    "site": "__PROYECTO__",
    "version": "sites/__PROYECTO__/versions/4a616a04137b499c"
  }
]
i  hosting[__PROYECTO__]: finalizing version...
[2019-08-19T20:24:22.542Z] >>> HTTP REQUEST PATCH https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c?updateMask=status  
 status=FINALIZED
[2019-08-19T20:24:22.708Z] <<< HTTP RESPONSE 500 vary=X-Origin, Referer, Origin,Accept-Encoding, content-type=application/json; charset=UTF-8, date=Mon, 19 Aug 2019 20:24:22 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:22.708Z] <<< HTTP RESPONSE BODY code=500, message=Internal error encountered., status=INTERNAL
Error: HTTP Error: 500, Internal error encountered.
[2019-08-19T20:24:22.710Z] Error Context: {
i  hosting[__PROYECTO__]: found 45 files in dist
[2019-08-19T20:24:18.645Z] [hosting] hash cache [ZGlzdA] load error: lines is not defined
[2019-08-19T20:24:19.209Z] [hosting] hash cache [ZGlzdA] stored for 45 files
[2019-08-19T20:24:19.210Z] [hosting][hash queue][FINAL] max=551, min=23, avg=51.46666666666667, active=0, complete=45, success=45, errored=0, retried=0, total=45, elapsed=564
[2019-08-19T20:24:19.210Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c:populateFiles  
 <request body omitted>
[2019-08-19T20:24:19.384Z] <<< HTTP RESPONSE 500 vary=X-Origin, Referer, Origin,Accept-Encoding, content-type=application/json; charset=UTF-8, date=Mon, 19 Aug 2019 20:24:19 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:19.385Z] <<< HTTP RESPONSE BODY code=500, message=Internal error encountered., status=INTERNAL
[2019-08-19T20:24:19.787Z] [populateQueue] Retrying task index 0
[2019-08-19T20:24:19.787Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c:populateFiles  
 <request body omitted>
i  hosting: adding files to version [0/45] (0%)
[2019-08-19T20:24:20.920Z] <<< HTTP RESPONSE 200 content-type=application/json; charset=UTF-8, vary=X-Origin, Referer, Origin,Accept-Encoding, date=Mon, 19 Aug 2019 20:24:20 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:20.924Z] [hosting][populate queue][FINAL] max=1137, min=1137, avg=1137, active=0, complete=1, success=1, errored=0, retried=1, total=1, elapsed=1716
[2019-08-19T20:24:20.924Z] [hosting] uploads queued: 7
[2019-08-19T20:24:22.540Z] [hosting][upload queue][FINAL] max=1620, min=1176, avg=1278.4285714285713, active=0, complete=7, success=7, errored=0, retried=0, total=7, elapsed=1620
✔  hosting[__PROYECTO__]: file upload complete
[2019-08-19T20:24:22.541Z] [hosting] deploy completed after 3910ms
[2019-08-19T20:24:22.542Z] [
  {
    "config": {
      "public": "dist",
      "ignore": [
        "firebase.json",
        "**/.*",
        "**/node_modules/**"
      ],
      "rewrites": [
        {
          "source": "**",
          "destination": "/index.html"
        }
      ],
      "site": "__PROYECTO__"
    },
    "site": "__PROYECTO__",
    "version": "sites/__PROYECTO__/versions/4a616a04137b499c"
  }
]
i  hosting[__PROYECTO__]: finalizing version...
[2019-08-19T20:24:22.542Z] >>> HTTP REQUEST PATCH https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c?updateMask=status  
 status=FINALIZED
[2019-08-19T20:24:22.708Z] <<< HTTP RESPONSE 500 vary=X-Origin, Referer, Origin,Accept-Encoding, content-type=application/json; charset=UTF-8, date=Mon, 19 Aug 2019 20:24:22 GMT, server=ESF, cache-control=private, x-xss-protection=0, x-frame-options=SAMEORIGIN, x-content-type-options=nosniff, alt-svc=quic=":443"; ma=2592000; v="46,43,39", accept-ranges=none, transfer-encoding=chunked
[2019-08-19T20:24:22.708Z] <<< HTTP RESPONSE BODY code=500, message=Internal error encountered., status=INTERNAL
Error: HTTP Error: 500, Internal error encountered.
[2019-08-19T20:24:22.710Z] Error Context: {
  "body": {
    "error": {
      "code": 500,
      "message": "Internal error encountered.",
      "status": "INTERNAL"
    }
  },
  "response": {
    "statusCode": 500,
    "body": {
      "error": {
        "code": 500,
        "message": "Internal error encountered.",
        "status": "INTERNAL"
      }
    },
    "headers": {
      "vary": "X-Origin, Referer, Origin,Accept-Encoding",
      "content-type": "application/json; charset=UTF-8",
      "date": "Mon, 19 Aug 2019 20:24:22 GMT",
      "server": "ESF",
      "cache-control": "private",
      "x-xss-protection": "0",
      "x-frame-options": "SAMEORIGIN",
      "x-content-type-options": "nosniff",
      "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,43,39\"",
      "accept-ranges": "none",
      "transfer-encoding": "chunked"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "firebasehosting.googleapis.com",
        "port": 443,
        "hostname": "firebasehosting.googleapis.com",
        "hash": null,
        "search": "?updateMask=status",
        "query": "updateMask=status",
        "pathname": "/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c",
        "path": "/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c?updateMask=status",
        "href": "https://firebasehosting.googleapis.com/v1beta1/sites/__PROYECTO__/versions/4a616a04137b499c?updateMask=status"
      },
      "method": "PATCH"
    }
  }
}
```

**Comment by benatkin** [comment]
The status page hasn't been updated. I hope this doesn't get counted as uptime, because everything that's already deployed is apparently still available. It's essential to be able to deploy in such a project as firebase hosting, which is supposed to have quick deploys. The deploys are pretty quick when it's working, but now it's not working for me. :(

**Comment by benatkin** [comment]
There appears to be some progress. I've now been able to deploy to each site! It works about a quarter of the time now, whereas before it was failing ever time I tried it for about 15 minutes, trying it about once a minute on average. So it seems like this will probably be fixed soon.

**Comment by Memeriaj** [comment]
[Status page has been updated](https://status.firebase.google.com/incident/Hosting/19012) (though obviously not nearly as helpful it it had already been there to begin with).

Did you sign-in to the CLI recently?  Or maybe need to re-authenticate?
Do you happen to be in Europe or on the US East coast?

Trying to narrow down some of our possibilities.

**Comment by FelixDQ** [comment]
I've also had the same issue. I'm in Europe deploying functions and hosting.  Re-authenticating didn't seem to have an effect. 

There doesn't seem to be any consistency as to which step of the process fails. Sometimes it failed almost immediately, and sometimes it failed at the end of the deployment. If I keep trying it will eventually get deployed without failing.

**Comment by gtgalone** [comment]
I have same issue. Can I use firebase functions in production? 
I am developing a new service with firebase functions and hosting for my company.
I am very curious.

**Comment by Memeriaj** [comment]
Are things working now?  East Coast and Europe might be marginally slower, but we think we have likely found the problem.

**Comment by Memeriaj** [comment]
Things should be working again.  Essentially one of the Hosting dependencies was returning errors about half the time in a particular region, which is why this was really only effecting people on the East Coast and in Europe.

**Comment by benatkin** [comment]
Yay! Thanks. I'm in Miami which is on the east coast. So that's probably why.

**Comment by franxois** [comment]
Hi,

status page is ok since 30 minutes but I still have 500 error when deploying from France

**Comment by aduranil** [comment]
I still have an issue with this as of 1 min ago

```[debug] [2019-08-21T15:00:01.948Z] <<< HTTP RESPONSE 500
[debug] [2019-08-21T15:00:01.948Z] <<< HTTP RESPONSE BODY
[error] 
[error] Error: HTTP Error: 500, Internal error encountered.

**Comment by SABRYX** [comment]
Error: HTTP Error: 500, Internal error encountered. FROM Egypt !!!!

**Comment by tlkiong** [comment]
Same but from Malaysia

**Comment by Adam-Mould** [comment]
Seems to be the same issue as 2 days ago. Functions can be deployed, but hosting cannot. UK based here.

**Comment by marcelolima** [comment]
Same in Berlin

**Comment by tad-iizuka** [comment]
Tokyo too...

**Comment by esantiagovieira** [comment]
Add Brazil to the loop as well, but it started today, as I am pretty sure I ran a deploy yesterday afternoon (GMT-3)

**Comment by luanch** [comment]
It started by 12:00 PM here in Brazil too.

**Comment by marknelissen** [comment]
3 hours ago it was working, now it is down, for deployment to Europe-West1.

**Comment by carvalhoMoreira** [comment]
Brazil is off too. Getting error HTTP 500: Internal error on deploying to firebase hosting. It started by 12:00 PM

**Comment by thandaanda** [comment]
India too...

**Comment by Ahmad-G-Mustafa** [comment]
Same in Egypt

**Comment by aduranil** [comment]
issue appears to be fixed now

**Comment by Memeriaj** [comment]
Yeah, it was basically the same thing that had happened on Monday, [this issue](https://github.com/firebase/firebase-tools/issues/1616#issuecomment-523673735) has a little bit more detail and the [incident itself](https://status.firebase.google.com/incident/Hosting/19013) has slightly more.

**Comment by lejard-h** [comment]
Still having the issue in France :/

**Comment by lejard-h** [comment]
It started friday (Aug 23) 
and yes it is every time I am trying to deploy `firebase deploy --only hosting`

with the following response
```
Error Context: {
  "body": {
    "error": {
      "code": 500,
      "message": "Internal error encountered.",
      "status": "INTERNAL"
    }
  },
  "response": {
    "statusCode": 500,
    "body": {
      "error": {
        "code": 500,
        "message": "Internal error encountered.",
        "status": "INTERNAL"
      }
    },
    "headers": {
      "vary": "X-Origin, Referer, Origin,Accept-Encoding",
      "content-type": "application/json; charset=UTF-8",
      "date": "Mon, 26 Aug 2019 14:37:06 GMT",
      "server": "ESF",
      "cache-control": "private",
      "x-xss-protection": "0",
      "x-frame-options": "SAMEORIGIN",
      "x-content-type-options": "nosniff",
      "alt-svc": "quic=\":443\"; ma=2592000; v=\"46,43,39\"",
      "accept-ranges": "none",
      "connection": "close"
    },
    "request": {
      "uri": {
        "protocol": "https:",
        "slashes": true,
        "auth": null,
        "host": "firebasehosting.googleapis.com",
        "port": 443,
        "hostname": "firebasehosting.googleapis.com",
        "hash": null,
        "search": null,
        "query": null,
        "pathname": "/v1beta1/sites/staging-alfred/versions",
        "path": "/v1beta1/sites/staging-alfred/versions",
        "href": "https://firebasehosting.googleapis.com/v1beta1/sites/staging-alfred/versions"
      },
      "method": "POST"
    }
  }
}
```

**Comment by woutertinbergen** [comment]
same issue here; been there for serveral days now...
**a POST to "Versions" gives the internal 500.**

[debug] [2019-08-27T06:39:40.156Z] >>> HTTP REQUEST POST https://firebasehosting.googleapis.com/v1beta1/sites/PROJECTKEY/versions  

[debug] [2019-08-27T06:39:41.584Z] <<< HTTP RESPONSE 500
[debug] [2019-08-27T06:39:41.584Z] <<< HTTP RESPONSE BODY

**Comment by woutertinbergen** [comment]
+1, I did not disable it either.. 
Thanks for pointing it out @Memeriaj

**Comment by sionlanini** [comment]
Same for me too. I definitely didn't disable it, so not sure why the sudden change.
