### ISSUE TITLE
PERMISSION_DENIED when using Firebase Admin SDK and Firestore Emulator

### ISSUE THREAD

**Issue by sgr-ksmt** [firebase/firebase-tools#2310]
### [REQUIRED] Environment info
- firebase-tools: 8.4.1
- firebase-admin: 8.12.1
- firebase-functions: 3.6.1
- (@firebase/testing: ^0.19.6)
- node: v10.17.0

**Platform:**
macOS

### [REQUIRED] Test case
I have a minimal Cloud Functions code and `firestore.rules`:

```ts
import * as functions from 'firebase-functions'
import * as admin from 'firebase-admin'

admin.initializeApp()

export const userCreated = functions.firestore.document('users/{userID}').onCreate(async (snapshot, context) => {
  const userRef = admin.firestore().collection('users').doc(context.params.userID)
  const user = await userRef.get()
  console.log(`user: ${user.data()}`)
  await userRef.update({ age: 30 })
  return undefined
})
```

```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if false;
    }
  }
}
```

In the function, I call `admin.firestore().collection(...).doc(...).get()` to get/update a user document from DB.
In the rules, I restrict all operations. But admin SDK can operate without the influence of `firestore.rules`

I setup emulators and ran `firebase emulators:start --only functions,firestore`, then I ran test:

```ts
import 'jest'
import * as firebase from '@firebase/testing'

// Please input your firebase project id.
const REAL_FIREBASE_PROJECT_ID = 'your-firebase-project-id'

describe('test user.onCreate', () => {
  let unsubscribe: any
  afterAll(() => {
    firebase.clearFirestoreData({ projectId: REAL_FIREBASE_PROJECT_ID })
    if (unsubscribe) {
      unsubscribe()
    }
  })
  describe('created company', () => {
    test('primary company should be set in user', async done => {
      const db = firebase
        .initializeAdminApp({ projectId: REAL_FIREBASE_PROJECT_ID })
        .firestore()

      const userRef = db.collection('users').doc('bob')
      await userRef.set({ name: 'bob' })

      unsubscribe = userRef.onSnapshot(snap => {
        console.log(snap.data())
        if (snap.data() && snap.data()!.age === 30) {
          done()
        }
      })
    })
  })
})
```

Finally, I got error:

```
i  functions: Beginning execution of "userCreated"
⚠  functions: Error: 7 PERMISSION_DENIED: 
false for 'get' @ L5
    at Object.callErrorFromStatus (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/@grpc/grpc-js/build/src/client.js:328:49)
    at Object.onReceiveStatus (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.handleTrailers (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:266:14)
    at ClientHttp2Stream.stream.on (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:315:26)
    at emitThree (events.js:136:13)
    at ClientHttp2Stream.emit (events.js:217:7)
Caused by: Error
    at Firestore.getAll (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/@google-cloud/firestore/build/src/index.js:687:23)
    at DocumentReference.get (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/@google-cloud/firestore/build/src/reference.js:199:32)
    at exports.userCreated.functions.firestore.document.onCreate (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/lib/index.js:9:32)
    at cloudFunction (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/firebase-functions/lib/cloud-functions.js:132:23)
    at runFunction (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:553:20)
    at /Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:538:19
    at Generator.next (<anonymous>)
    at /Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/foobar/src/github.com/user/plane-emulator-sandbox/functions/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:4:12)
⚠  Your function was killed because it raised an unhandled error.
```

But this function worked perfectly when I deployed it to Firebase.

I think `admin.firestore()` is usually NOT affected by `firestore.ruels`.
But actually it was affected by `firestore.rules` while running firestore, functions emulator.

btw, if `yarn.lock` is updated as follows, it will work while running emulators:

https://github.com/sgr-ksmt/plain-emulator-sandbox/pull/1

It's so confusing..

Maybe it's because of some of dependencies, but I don't know why it works when I change `yarn.lock`.

### [REQUIRED] Steps to reproduce

I prepared sample project here: https://github.com/sgr-ksmt/plain-emulator-sandbox

This sample was made from scratch(created a new repository, ran `firebase init`, install latest dependencies).

```
git clone path/to/project
cd functions/
yarn
yarn test
```

### [REQUIRED] Expected behavior

`admin.firestore().collection(...).doc(...).get()` will be successful and should not be affected by `firestore.rules`

### [REQUIRED] Actual behavior

`admin.firestore().collection(...).doc(...).get()` was failed due to permission denied. It was affected by `firestore.rules`

**Comment by mono0926** [comment]
I confirmed that **`firebase-admin`** was broken **after [`8.11.0`](https://github.com/firebase/firebase-admin-node/releases/tag/v8.11.0)**.

`firebase-admin 8.10.0`  works fine.

package-lock.json diff between firebase-admin 8.10.0 and 8.11.0: [0001-a.patch.zip](https://github.com/firebase/firebase-tools/files/4710351/0001-a.patch.zip)

**Comment by samtstern** [comment]
@sgr-ksmt @mono0926 thanks for the information.  This seems like it may be related to this change:
https://github.com/googleapis/nodejs-firestore/releases/tag/v3.8.2

**Comment by samtstern** [comment]
Ok I was able to confirm that this is a bug in `@google-cloud/firestore` since I was able to reproduce the bug as described above but fixed it by pinning that dependency:

```js
  "dependencies": {
    "firebase-admin": "^8.12.1",
    "firebase-functions": "^3.6.2",
    "@google-cloud/firestore": "3.8.1"  // <-- PINNED THIS
  },
```

**Comment by mono0926** [comment]
@samtstern 

I also confirmed that, you're right! Thanks 👍

**Comment by samtstern** [comment]
I was also able to confirm this is a pure Firestore SDK bug and has no relation to the Functions emulator by writing this script:

```
const admin = require('firebase-admin');
admin.initializeApp();

async function main() {
  const res = await admin.firestore().doc('foo/bar').set({
    date: new Date().toISOString()
  });
  console.log(`WriteResult: ${res}`);
}

if (require.main === module) {
  main();
}
```

And running it like this:
```bash
$ GCLOUD_PROJECT=<...> FIRESTORE_EMULATOR_HOST=<...> node functions/index.js 
```

**Comment by samtstern** [comment]
Filed this issue to track the underlying bug:
https://github.com/googleapis/nodejs-firestore/issues/1104

However I will leave this open here as well since it's likely to affect emulator users and I want this to be visible.

**Comment by sgr-ksmt** [comment]
@mono0926 @samedson 
I really appreciate your investigation 😄 
I confirmed https://github.com/firebase/firebase-tools/issues/2310#issuecomment-636839936 too.

**Comment by samtstern** [comment]
This has been fixed by `@google-cloud/firestore` version `3.8.4`:
https://github.com/googleapis/nodejs-firestore/releases/tag/v3.8.4

You should be able to get this version by deleting your `package-lock.json` and running `npm install again`

**Comment by srolfe26** [comment]
**firebase-tools:**
- firebase-tools: 8.4.1

 - @google-cloud/firestore: 3.8.4
 - firebase-admin: 8.12.1
 - firebase-functions: 3.6.2
 - firebase-tools: 7.16.2
 - @firebase/testing: 0.19.6

**Platform:**
 - macOS

Cloud functions are still not running in a trusted context from the emulator. When I have a firestore triggered cloud function, it runs subject to my firestore rules. When I edit the firestore rules the function runs with no problems, but my understanding is those rules shouldn't apply?

**Comment by samtstern** [comment]
@srolfe26 this is very surprising to me.  Just to be clear: you're running the Functions and Firestore emulators together and you're seeing PERMISSION_DENIED for writes originating within the Functions emulator?

If that's the case can you try and show me the smallest possible setup to reproduce this?

**Comment by srolfe26** [comment]
@samtstern Of course :-)

This was all working code before I updated the firebase packages. I also recently reverted to an older version of firebase-tools and then came back to 8.4.1. Upon coming back, I now get this error.

'TypeError: Channel credentials must be a ChannelCredentials object'

*firestore rules set to simply allow:*
```
rules_version = '2';
service cloud.firestore {
    match /databases/{database}/documents {
        match /{document=**} {
            allow read: if request.auth.token.is_admin == true;
            allow write: if request.auth.token.is_admin == true;
        }

        match /persons/{personId} {
            allow read: if (personId == request.auth.uid)
            allow create: if (personId == request.auth.uid)
            allow update: if (personId == request.auth.uid)
        }
    }
}
```

*index.js*
```
exports.personUpdate = functions.firestore.document('persons/{PersonId}').onWrite(Person.personUpdate);
```

*personUpdate snippet*
```
// ...
// this is the offending statement according to the logs
const people = await this.db.collection(Person.COLLECTION).get().then(querySnapshot => {
    const persons = [];
    querySnapshot.forEach(doc => persons.push(new Person(doc)));
    return persons;
});
// ...

**Comment by yuchenshi** [comment]
@srolfe26 

> 'TypeError: Channel credentials must be a ChannelCredentials object'

This looks a lot like https://github.com/firebase/firebase-tools/issues/2207 and tl;dr it's highly likely to be caused by grpc dependency issue.

Try removing your `node_modules` directory (and maybe also `package-lock.json`) and `npm i` again. If things still don't work, attach `npm ls` output first, and then try again with a fresh new directory `npm init && npm i -S firebase-admin@8.12.1`.

**Comment by turboza** [comment]
In case this is useful. After I tried the fix from https://github.com/firebase/firebase-tools/issues/2310#issuecomment-638471674, I got the new issue.

```
⚠  functions: Cannot set property config of #<Object> which has only a getter
⚠  Your function was killed because it raised an unhandled error.
```

And it ended up because my firebase cli has not been updated since I used to old version. So the fix is..

```
npm install -g firebase-tools
```

```
firebase --version
8.4.2
```

And this firebase cli version with the following package works fine for me now! 🎉 

```json
"dependencies": {
    "firebase-admin": "^8.12.1",
    "firebase-functions": "^3.6.2"
}
```

**Comment by samtstern** [comment]
@turboza glad thinks started working for you with the latest versions!
