### ISSUE TITLE
firebase deploy --only functions = [ERR_UNSUPPORTED_ESM_URL_SCHEME]

### ISSUE THREAD

**Issue by fouchekeagan** [firebase/firebase-tools#3689]
### [REQUIRED] Environment info

**firebase-tools:** 9.16.5

**Platform:** Windows 10

**Node:** 14.17.3

**NPM:** 6.14.13

Package.json Dep:

**Firebase:** 8.9.1
**@google-cloud/functions-framework:** 1.9.0
**firebase-functions:** 3.15.4
**Typescript:** 4.3.5

### [REQUIRED] Steps to reproduce

1. Upgrade from node 10 to node 14 (update from commonJS to ESM).
2. Attempt to deploy.

### [REQUIRED] Expected behavior

The firebase functions to be deployed.

### [REQUIRED] Actual behavior

Deploy fails while running pre-deploy script:  
```Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'```

![image](https://user-images.githubusercontent.com/72212540/129882917-a09c0c88-1efc-4370-935d-b70956f9116d.png)

Additional info: 
The same is shown if I specify a single function.
We had previously an issue with starting the emulators when initially updating to Node14 - this was resolved by #2994 /  #3573 /  #3574 (Thanks Daniel Lee!)
I can start the emulators and use the functions locally.

**Comment by taeold** [comment]
@fouchekeagan Thanks for reporting the issue!

It looks like I forgot to apply the fix to module path issue on Windows (https://github.com/firebase/firebase-tools/pull/3574) to the code path relevant to function deploys (https://github.com/firebase/firebase-tools/blob/7f99ac5868cf2c2265ff0923c8889d90c16c51c5/src/deploy/functions/runtimes/node/triggerParser.js#L24) 🤦‍♂️

**Comment by taeold** [comment]
I will try to get the fix merged soon so that the bug is fixed by next CLI release.

In the meantime, if anyone is willing to test out the fix (I don't have a Windows machine), I'd appreciate it:

```
> git clone https://github.com/firebase/firebase-tools.git
> cd firebase-tools
> git checkout origin/dl-cf3-esm-windows-fix2 
> npm i
> npm run build
> npm link # firebase cli should now point to locally built one
# cd to your functions project
> firebase deploy --only functions
```

**Comment by fouchekeagan** [comment]
Thanks for the speedy response.
I tested the fix and was able to successfully deploy my functions!
Much appreciation for your help resovling this issue!

I'll leave this issue for you to close when it's merged?

**Comment by taeold** [comment]
@fouchekeagan Thanks a bunch for giving it a go. Yep that's the plan - I will close the ticket after our next CLI release.

**Comment by PMLS3** [comment]
[> npm run build](https://github.com/firebase/firebase-tools/issues/3689#issuecomment-902108291)



> I will try to get the fix merged soon so that the bug is fixed by next CLI release.
> 
> In the meantime, if anyone is willing to test out the fix (I don't have a Windows machine), I'd appreciate it:
> 
> ```
> > git clone https://github.com/firebase/firebase-tools.git
> > cd firebase-tools
> > git checkout origin/dl-cf3-esm-windows-fix2 
> > npm i
> > npm run build
> > npm link # firebase cli should now point to locally built one
> # cd to your functions project
> > firebase deploy --only functions
> ```

I have done this step by step, I am still getting: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader

Any Assistance will be appreciated

**Comment by taeold** [comment]
@PMLS3 Can you try running the latest CLI version (the change has been released for few months):

```
npm i -g firebase-tools
```
