### ISSUE TITLE
Project-specific .env files aren't loaded when running functions emulator

### ISSUE THREAD

**Issue by larrifax** [firebase/firebase-tools#4239]
### [REQUIRED] Environment info

**firebase-tools:** 10.2.1

**Platform:** Ubuntu

### [REQUIRED] Test case

The documentation around environment variables using .env-files while using the local functions emulator states the following:

> Contents of .env.local take precedence over .env and the project-specific .env file
> Source: https://firebase.google.com/docs/functions/config-env#emulator_support

However, when running locally the project-specific .env file isn't even loaded, only the `.env` and `.env.local` is.
And indeed, the source code doesn't even attempt to load project-specific files when running in an emulator setting:

https://github.com/firebase/firebase-tools/blob/5a8bd4e4337536821a258fa7d14cdc11d431c478/src/functions/env.ts#L199-L206

According to my interpretation of the documentation linked above, there's a mismatch between the documentation and the implementation, which should be resolved one way or another.

### [REQUIRED] Steps to reproduce

1. Add a `.env`, `.env.development` and `.env.local` file to your project, filling them with different environment variables
2. `firebase use development`
3. `firebase emulators:start --only functions`
4. Trigger a function

### [REQUIRED] Expected behavior

Functions emulator is started, and logs should show that all relevant `.env*` files are loaded:
`i  functions: Loaded environment variables from .env, .env.development, .env.local.`

### [REQUIRED] Actual behavior

Functions emulator is started, but logs shows that the project specific .env file isn't loaded (`.env.development` is missing from output):
`i  functions: Loaded environment variables from .env, .env.local.`

**Comment by jaytavares** [comment]
I'm seeing this same behavior.

**Comment by taeold** [comment]
Thanks for a thorough writeup. I think the documentation is right and the implementation is wrong. We will work on a fix to be shipped in the next release.

**Comment by larrifax** [comment]
Thanks @taeold. This is maybe another bug/feature request, but I also noticed that .env variables aren't available when the "startup code" is ran, so it's currently not possible to e.g. store the region in an environment variable and use it like so:

`functions/index.js`:
```
import * as functions from "firebase-functions";
import * as callable from "./callables";

export const someFunction = functions.region(process.env.REGION).https.onCall(callable.someFunction);
```
The environment variables aren't available to use at the time when `.region()` or `.runWith()` are evaluated. They're only available "within `onCall`".

Is this something you're aware of/decided not to support? Or should I create a new bug/feature request for it?

**Comment by pradella** [comment]
In my case, when I start the emulator the message below is not even showing:

`i functions: Loaded environment variables from .env, .env.local.`

**Comment by jtfrom9** [comment]
https://github.com/firebase/firebase-tools/issues/4239#issuecomment-1063763689

Hi @taeold, could you comment on the above point?
I’m also hoping .env variables are available on `.region()` or  `.runWith()` are evaluated

**Comment by michaelalhilly** [comment]
@taeold Hi. This is still not working for me locally. The variables are loaded from .env if I remove the .env.local file but the variables are not loaded at all if I add a .env.local file. I'm also importing variables from Secrets Manager which is working fine. Is this suppose to be working now.

**Comment by erikkjernlie** [comment]
`.env` variables are only available during application _runtime_, and not when you are deploying. You have to use Firebase's remote config if you want to use env variables when initializing functions, e.g. `functions.config().environment.isDev`.

**Comment by juane1000** [comment]
> `.env` variables are only available during application _runtime_, and not when you are deploying. You have to use Firebase's remote config if you want to use env variables when initializing functions, e.g. `functions.config().environment.isDev`.

This is the old method for environment variables and what I used in previous projects. However, though not directly said in the docs, their language about migrating to the new .env method and how "config" is removed from V2 cloud functions makes me worry that it may be deprecated in the not too distant future.

My hope is that this is an oversight as @larrifax mentioned.

**Comment by Wian-TMC** [comment]
Why is this closed ?

You cannot deploy to `v2` of functions when using `functions.config()`, and that seems to be the only solution for accessing any deployment variables. This is a big issue

**Comment by NickVanzo** [comment]
Same here, my .env or .env.local files are not loaded when I start the emulator

**Comment by erikkjernlie** [comment]
`.env` variables are loaded into the application runtime (after the configuration in the beginning), so you need to use remoteConfig for using env variables during deploy :)

**Comment by juane1000** [comment]
> `.env` variables are loaded into the application runtime (after the configuration in the beginning), so you need to use remoteConfig for using env variables during deploy :)

Can you elaborate on this? I thought remoteConfig was for user facing apps.

**Comment by Wian-TMC** [comment]
> `.env` variables are loaded into the application runtime (after the configuration in the beginning), so you need to use remoteConfig for using env variables during deploy :)

Please refer here for a rationale of the previous, current and future solution. Please note, Remote Config is deprecated and cannot be used when deploying v2 functions.

https://github.com/firebase/firebase-functions/issues/1084

**Comment by michaelalhilly** [comment]
Thanks for reopening this. It would be great if this could work as expected.

**Comment by edonosotti** [comment]
**IMPORTANT NOTE**

Please verify that you did not set any variable using a [reserved name](https://firebase.google.com/docs/functions/config-env#reserved-names).

If you do that, the emulator will just fail silently upon loading the functions and not load your `.env[.*]` files.

**Comment by Wian-TMC** [comment]
> firebase/firebase-functions#1084

You're missing the point of the issue at hand. Please refer to https://github.com/firebase/firebase-functions/issues/1084

**Comment by irux** [comment]
any news on this ?

**Comment by CarlosDuarte17** [comment]
I had the same problem, please check that no keys in the .env file are empty.

**Comment by bruceharrison1984** [comment]
Just ran into this. Very painful having to deploy my functions just to see if they work, despite having a perfectly good local emulator.

You can kind of hack around it by bringing in `dotenv` and loading the files if `NODE_ENV === development`. I actually was going this, then read the docs so I removed it, only to find it was broken.

**Comment by nonam4** [comment]
> _EDIT_ Turns out I am an idiot and had a FIREBASE_ setting in my .env file. Removing it fixed the issue, though I still don't get the console message informing me that the env files have been loaded.

If you're having problem with process.env in firebase functions this should help

**Comment by myktra** [comment]
I had this same problem - removed a `FIREBASE_xxx` variable from my .env file and the variables loaded. Unfortunate an exception isn't thrown when the documented policy is unknowingly violated. Variables from the .env file are loaded at runtime, so if you attempt to call your function from the shell for example, you should see the following in the console:

```
firebase > myFunction({ test: '123' })
Sent request to function.
firebase > i  functions: Loaded environment variables from .env.
```

**Comment by knownasilya** [comment]
Unsure if related, but `firebase functions:shell` doesn't load `.env.local` file. It says it loads `.env`, and the values that are present on `process.env` confirm it.

**Comment by blidd-google** [comment]
Hi all, thanks for helping us and others diagnose issues with loading environment variables in the functions emulator. Two things:

1) Parameterized configuration is now the recommended way to configure your environment variables. Please refer to the docs [here](https://firebase.google.com/docs/functions/config-env#reserved-names) for instructions on how to use params. Check out the thread [here](https://github.com/firebase/firebase-functions/issues/1084) for context about the params feature (thanks to @Wian-TMC for sharing).
2) I will be closing this issue, as the original error has been resolved in #4273. If you are still encountering issues with configuring your environment, please open a new issue and provide instructions on how to reproduce your error.

**Comment by ekalosak** [comment]
This is still broken @blidd-google , please consider re-opening.
In a slightly different bent, the `.env.local` method for [overriding environment variables on a development workstation](https://firebase.google.com/docs/functions/config-env?gen=2nd#emulator_support) is broken.

Details: https://github.com/firebase/firebase-functions/issues/1094#issuecomment-1740035705

**Comment by Stf-F** [comment]
Currently facing this issue as well and I believe that this started failing after the creation of several aliases. None of my .env files are being read in the emulator, not even in the body of the function. I worked around the issue by installing the `dotenv` package. Not ideal but couldn't waste anymore time looking into this.

**Comment by conor909** [comment]
At the moment my project alias named env files are not being used, I have `.env.dev` & `.env.prod`, but at the moment I need to copy the contents into a `.env` file before deploying to `dev` or `prod`

**Comment by a7md0** [comment]
Same issue here, the deployment is failing due to the code requiring an environment variable to exists. The variable is already defined in the `.env` and no reserved name is being used in the file. Still the deployment does not print the below line (which is documented in Firebase)

```bash
$ firebase deploy --only functions
# ...
# i functions: Loaded environment variables from .env.
# ...
```

Using `"firebase-functions": "^4.6.0"` & `"firebase-tools": "^13.0.2"`

**Comment by mustafaekim** [comment]
Hi, I need to setup a custom environmental variable so that a private npm package that we include into the firebase/functions can configure itself accordingly however it seems like there is no single way for configuring environmental variables in gen2?

**Comment by rzfang** [comment]
Hi, here
Not sure if this can help. I don't run emulator, I run deploy directly, and what I found is working for me.

Move the .env* files out of functions directly to the root of your directory, and everything works.

In my case, I have 3 .env files: .env, .env.beta, .env.prod
with the command `firebase use beta && ... && firebase deploy ...`, the log will show the line:
```
i  functions: Loaded environment variables from .env, .env.beta.
```
instead of 
```
i  functions: Loaded environment variables from .env.
```

**Comment by rendomnet** [comment]
Why this is CLOSED?
