### ISSUE TITLE
firebase deploy hosting with webframeworks experiment fails on arm mac

### ISSUE THREAD

**Issue by lesnitsky** [firebase/firebase-tools#5357]
### [REQUIRED] Environment info

**firebase-tools:** 
11.19.0

**Platform:**

macOS arm

### [REQUIRED] Steps to reproduce

- create new Next.js project
- enable webframeworks experiment
- run firebase init hosting
- run `firebase deploy`

### [REQUIRED] Expected behavior

deploy succeeds

### [REQUIRED] Actual behavior

Error

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for inotify@1.4.6: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64
```

### firebase-debug.log

```
[debug] [2022-12-21T15:14:41.717Z] Error: Command failed: npm i --omit dev --no-audit
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at execSync (pkg/prelude/bootstrap.js:2115:30)
    at prepareFrameworks (/Users/lesnitsky/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/frameworks/index.js:335:42)
    at async deploy (/Users/lesnitsky/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/deploy/index.js:53:13)
[error] 
[error] Error: An unexpected error has occurred.
```

### Additional info

Running `npm i --omit dev --no-audit` manually in the project directory throws no error

**Comment by mcarriere** [comment]
I have the same error on an Intel Mac doing `firebase deploy --only=functions`. Works fine if I revert to firebase-tools@v11.18.0

**Comment by carlwicker** [comment]
I have the same [error] "Error: An unexpected error has occurred" on `firebase deploy`

**Comment by Erfa** [comment]
I see the same problem with `firebase start:emulators` as well on a my M1 MacBook Air. Downgrading to 11.18.0 solves it, thanks!

**Comment by leo-paz** [comment]
I'm still getting this on an m1 macbook pro. I tried using firebase-tools@v11.18.0 as well as higher and lower versions

**Comment by jamesdaniels** [comment]
This should be addressed in recent releases, please file a new issue if you see any issues on Apple Silicon.

**Comment by assmabenmussa** [comment]
I got the same error and it is very frustrating, has anyone figured out how to fix it?

**Comment by paulrrdiaz** [comment]
@assmabenmussa work for me after `npm i -g firebase-tools@11.18.0`, also node -v v16.14.2 / npm -v 8.5.0

**Comment by lesnitsky** [comment]
@jamesdaniels still reproducible on firebase tools `11.29.1`. See #5773

**Comment by juanpa097** [comment]
@jamesdaniels 
Hi James Daniels,

I can still repro the same error with version `12.2.1`. This is my full trace:
```
➜  teapptro-creator git:(main) ✗ firebase deploy

   Thank you for trying our early preview of Next.js support on Firebase Hosting.
   During the preview, support is best-effort and breaking changes can be expected. Proceed with caution.

   Documentation: https://firebase.google.com/docs/hosting/frameworks/nextjs
   File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
   Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

   We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X

- info Loaded env from /Users/juanpenaloza/Developer/teapptro-creator/.env.local
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for inotify@1.4.6: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/juanpenaloza/.npm/_logs/2023-05-30T17_59_31_895Z-debug.log

Error: An unexpected error has occurred.
```

Please let me know if there is any other log I can share to address this issue.

Thank you! 🙏
