### ISSUE TITLE
firebase deploy with webframeworks (nextjs) experiments no longer work on firebase-tools@12.2.0

### ISSUE THREAD

**Issue by lsy90** [firebase/firebase-tools#5896]
###  Environment info

**firebase-tools:12.2.0**

**Platform:macOS**

### Test case
Follow exactly the steps in https://firebase.google.com/docs/hosting/frameworks/nextjs

After running `firebase deploy`, you will be presented with the error `Directory 'hosting/public' for Hosting does not exist.`

###  Steps to reproduce

Follow exactly the steps in https://firebase.google.com/docs/hosting/frameworks/nextjs. 

`firebase.json`
```json
{
  "hosting": {
    "source": "hosting",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "frameworksBackend": {
      "region": "asia-east1"
    }
  }
}
```
This issue does not happen in `firebase-tools@12.1.0`

###  Expected behavior

Should deploy nextjs app instead of treating it as a client web app.

###  Actual behavior
```
[2023-05-25T01:14:30.573Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2023-05-25T01:14:30.574Z] > authorizing via signed-in user (***)
[2023-05-25T01:14:30.574Z] [iam] checking project webexperiement-test for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[2023-05-25T01:14:30.576Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/webexperiement-test:testIamPermissions [none]
[2023-05-25T01:14:30.576Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/webexperiement-test:testIamPermissions x-goog-quota-user=projects/webexperiement-test
[2023-05-25T01:14:30.576Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/webexperiement-test:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[2023-05-25T01:14:31.692Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/webexperiement-test:testIamPermissions 200
[2023-05-25T01:14:31.693Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/webexperiement-test:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[2023-05-25T01:14:31.695Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/webexperiement-test [none]
[2023-05-25T01:14:32.214Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/webexperiement-test 200
[2023-05-25T01:14:32.214Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/webexperiement-test {"projectId":"webexperiement-test","projectNumber":"745032223670","displayName":"webexperiement-test","name":"projects/webexperiement-test","resources":{"hostingSite":"webexperiement-test"},"state":"ACTIVE","etag":"1_cbbafdb9-7e24-42b6-a7e9-ca49ed62f668"}

   Thank you for trying our early preview of Next.js support on Firebase Hosting.
   During the preview, support is best-effort and breaking changes can be expected. Proceed with caution.

   Documentation: https://firebase.google.com/docs/hosting/frameworks/nextjs
   File a bug: https://github.com/firebase/firebase-tools/issues/new?template=bug_report.md
   Submit a feature request: https://github.com/firebase/firebase-tools/issues/new?template=feature_request.md

   We'd love to learn from you. Express your interest in helping us shape the future of Firebase Hosting: https://goo.gle/41enW5X

- event compiled client and server successfully in 441 ms (151 modules)
Effective firebase.json:
[
  {
    "source": "hosting",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "frameworksBackend": {
      "region": "asia-east1"
    },
    "site": "webexperiement-test",
    "rewrites": [],
    "redirects": [],
    "headers": [],
    "cleanUrls": true,
    "public": "hosting/public",
    "webFramework": "next"
  }
]

=== Deploying to 'webexperiement-test'...

i  deploying hosting 
[2023-05-25T01:14:40.983Z] >>> [apiv2][query] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/webexperiement-test/versions [none]
[2023-05-25T01:14:40.983Z] >>> [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/webexperiement-test/versions {"status":"CREATED","labels":{"deployment-tool":"cli-firebase","firebase-web-framework":"next"}}
[2023-05-25T01:14:41.823Z] <<< [apiv2][status] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/webexperiement-test/versions 200
[2023-05-25T01:14:41.823Z] <<< [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/webexperiement-test/versions {"name":"projects/745032223670/sites/webexperiement-test/versions/211f160594a23c5c","status":"CREATED","config":{},"labels":{"firebase-web-framework":"next","deployment-tool":"cli-firebase"}}
i  hosting[webexperiement-test]: beginning deploy... 

Error: Directory 'hosting/public' for Hosting does not exist.
```

**Comment by cd-blanche** [comment]
Hey getting this same error too with webframeworks and Vite, took us a few hours to find out the issue wasn't with our code but rather a bug with firebase-tools v12.2.0 

Just downgraded to v12.1.0 and it deploys perfectly fine now

**Comment by jamesdaniels** [comment]
Sorry for the continued instability here & thanks for trying out our experiment! 

The current work around is to stick with the prior CLI release (as has been discovered) or force the production bundle with the new environment variable (the one who's addition has caused all this fuss 😛 ) `FIREBASE_FRAMEWORKS_BUILD_TARGET=production firebase deploy`.

The fixes have been merged and will be in the next release of the CLI. If you're eager to give them a spin feel free to install the CLI via the github incantation: `npm i -g github:firebase/firebase-tools`

**Comment by jamesdaniels** [comment]
Going to leave the issue open until the fix is deployed.

**Comment by supunTE** [comment]
> Hey getting this same error too with webframeworks and Vite, took us a few hours to find out the issue wasn't with our code but rather a bug with firebase-tools v12.2.0
> 
> Just downgraded to v12.1.0 and it deploys perfectly fine now

Encountered the same issue with next js, downgrading firebase tools worked

**Comment by shawn1130** [comment]
I am using `firebase-tools v12.2.1` and when running `firebase deploy` errors out with `Error: firebase serve does not support Next.js Middleware. Please use firebase emulators:start instead.` 

I tried using the `FIREBASE_FRAMEWORKS_BUILD_TARGET=production firebase deploy` which causes the deployment to be successful but then when accessing the app it gives a `Internal Server Error 500` on load. 

Upon checking the log of the `ssr function` the log shows the following error `Error: Process exited with code 1`

removing the `middleware.js` causes the deployment to go thru and the app loads but with other weird behaviors like the image assets not being loaded.

My apologies for any missing information. I am new to development.

**Comment by diegoasua** [comment]
Found a similar issue. Had to downgrade `firebase-tools` to v12.1.0`. Deployment was still failing with `next` to `13.4.4`. Uninstalled `next` and clean install `13.4.2` worked.

**Comment by brettpoulin** [comment]
Also took a few hours before I realized it might not be my code causing my deployment to fail and got here, but downgrading to firebase-tools 12.1.0 fixed the issue. 
sudo npm remove -g firebase-tools
sudo npm install -g firebase-tools@12.1.0

**Comment by jamesdaniels** [comment]
firebase-tools 12.3.0 is released with this fix now

**Comment by MiftahClassifieds** [comment]
'ERROR: cannot find the next exucutable' this what i got running 'firebase deploy' with firebase-tools@latest. downgrading to firebase-tools@12.1.0 resolve the issue as mentioned guys above thank u to them
