### ISSUE TITLE
The default Firebase app does not exist. Make sure you call initializeApp()

### ISSUE THREAD

**Issue by christhompsongoogle** [firebase/firebase-tools#5980]
### Discussed in https://github.com/firebase/firebase-tools/discussions/5910

From [Geoffrey-Pliez](https://github.com/Geoffrey-Pliez)

> [Here](https://stackblitz.com/edit/github-bi9q8b?file=src%2Fpages%2Findex.astro) is the minimal source code to reproduce the problem.

When I test locally with the prod_preview command (set FIREBASE_FRAMEWORKS_BUILD_TARGET=production&& npm run emulators),
it works correctly and the code passes well in firebase-aware.

When I deploy on the server (firebase hosting) via the firebase deploy command, it no longer works and get the message
 [ssr] Error: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.
and guess that on the server the firebase-aware script is no longer called.

I'm not sure but I think it's since upgrading from 11.30.0 to 12.0.0

**Comment by steebchen** [comment]
I'm also running into this with next-firebase-auth it seems

**Comment by DellaBitta** [comment]
@Geoffrey-Pliez,

I'm from the Firebase Web SDK team. I was looking a bit into this issue and I'm trying to reproduce this here to see if this was a Firebase Web Frameworks issue or a Firebase Admin SDK issue.

I haven't been able to get this to work with the latest or older versions of the `firebase-admin` and `firebase-tools` SDKs. All versions seem to have problems at the build step (the same error as you reported) which is fixed by initializing the `firebase-admin` SDK [as described here](https://firebase.google.com/docs/admin/setup#add-sdk).

I should note that I was able to reproduce this issue without Firebase Web Framework support (from firebase-tools) simply by creating an Astro app from scratch. I went through these steps:

1. `npm create astro@latest` and walking through the configuration steps.
2. `npm install firestore-admin`.
3. Updating the code at the top of `index.astro` from:

```
---
import Layout from '../layouts/Layout.astro';
import Card from '../components/Card.astro';
---
```

to:

```
---
import Layout from '../layouts/Layout.astro';
import Card from '../components/Card.astro';

import { getFirestore } from 'firebase-admin/firestore'
const firestore = getFirestore()
---
```

4. `npm run build`.

This produces the same `Error: The default Firebase app does not exist` that you reported. The error goes away if I add:

```
import { initializeApp } from 'firebase-admin/app'
const app = initializeApp();
```

Could you step me how you've setup your environment past these steps to make this work with the older admin / firebase-tools versions without calling `initializeApp` first, as is the case in your provided code? 

Thanks very much.

**Comment by Geoffrey-Pliez** [comment]
@DellaBitta 


Sorry, I don't remember very well because currently I work around the problem by initializing firebase-admin in Astro middleware.

As soon as I have time, I will try to investigate why it worked before at home.

**Comment by aayman997** [comment]
Any updates on this issue?
I'm facing the same error but in Next.js _The default Firebase app does not exist. Make sure you call initializeApp()_
When I try to initializeApp() inside the API route or middleware?

**Comment by DellaBitta** [comment]
Hi @aayman997,

We don't have any new information about this issue. I don't have a reproducible test case beyond the originally reported one, which I had already detailed how I was able to fix the code to make it work.  If you have a different issue and setup then please create a new issue. Thanks!

**Comment by YusufTezel** [comment]
Hi
Sorry, but it doesn't work. Can you please be more specific about how to work around this issue which still persists?

**Comment by JoaquinFF** [comment]
Hello, are there any updates on how to solve this issue? I'm using nextjs and seems to work sometimes and sometimes it doesn't

**Comment by cyrilmano** [comment]
This is how I resolved this firebase initializeApp error: **The default Firebase app does not exist. Make sure you call initializeApp()**

**SOLUTION:**
I solved this just now by using the Firebase RestfulApi instead of firebase-admin sdk [HERE](https://firebase.google.com/docs/firestore/use-rest-api)

Let's say for example, you want to create a new document in a collection called "products". Your request might look like this:

```
POST /v1/projects/{project_id}/databases/{database_id}/documents/products?documentId={document_id} HTTP/1.1
Host: firestore.googleapis.com
Authorization: Bearer YOUR_OAUTH_TOKEN
Content-Type: application/json

{
  "fields": {
    "name": { "stringValue": "Product Name" },
    "price": { "integerValue": 100 }
  }
}
```
