### ISSUE TITLE
Firebase hosting: HTTP Error: 404, Requested entity was not found

### ISSUE THREAD

**Issue by phminella** [firebase/firebase-tools#6110]
Everything was working just fine yesterday. Last thing I did yesterday was to deploy the app and then update the firebase-tools to its latest version. And this morning it was no longer possible to deploy and this error pops up.
I can only assume it is related to update firebase-tools. But the error continues even downgrading it.
I tried to also update firebase, but no success.
The function to serve the nextjs app is created, but the website is not deployed. 

### [REQUIRED] Environment info

Firebase CLI 12.4.3

Firebase 10.0.0

Windows

### [REQUIRED] Test case

`./firebase.json`

```
{
  "hosting": {
    "source": ".",
    "ignore": ["firebase.json", "**/.*", "**/node_modules/**"],
    "frameworksBackend": {
      "region": "asia-east1"
    }
  }
}
```

`.firebasesrc`
```
{
  "projects": {
    "default": "[PROJECT_NAME]"
  }
}
```

### [REQUIRED] Steps to reproduce

firebase deploy

### [REQUIRED] Expected behavior

Properly deploy app

### [REQUIRED] Actual behavior

Error after creating nextjs function

```
i  hosting[PROJECT_NAME]: beginning deploy...
i  hosting[PROJECT_NAME]: found 633 files in .firebase\PROJECT_NAME\hosting
+  hosting[PROJECT_NAME]: file upload complete
i  functions: updating Node.js 18 (2nd Gen) function firebase-frameworks-PROJECT_NAME:ssrPROJECT_NAME(asia-east1)...
+  functions[firebase-frameworks-PROJECT_NAME:ssrPROJECT_NAME(asia-east1)] Successful update operation.
Function URL (firebase-frameworks-PROJECT_NAME:ssrPROJECT_NAME(asia-east1)): https://ssrPROJECT_NAME-xxxxxx-de.a.run.app
i  functions: cleaning up build files...
i  hosting[PROJECT_NAME]: finalizing version...

Error: HTTP Error: 404, Requested entity was not found.
```

`firebase-debug.log
`

This goes on repeat for around 100 lines, and no other message is printed. This is the end of the firebase-debug.log.

```
[debug] [2023-07-11T11:10:28.643Z] [create-firebase-frameworks-PROJECT_NAME-asia-east1-ssrPROJECT_NAME] Retrying task index 0
[debug] [2023-07-11T11:10:28.643Z] >>> [apiv2][query] GET https://cloudfunctions.googleapis.com/v2/projects/PROJECT_NAME/locations/asia-east1/operations/operation-1689073669967-600341c191066-017485c2-df7ba452 [none]
[debug] [2023-07-11T11:10:28.765Z] <<< [apiv2][status] GET https://cloudfunctions.googleapis.com/v2/projects/PROJECT_NAME/locations/asia-east1/operations/operation-1689073669967-600341c191066-017485c2-df7ba452 200
[debug] [2023-07-11T11:10:28.765Z] <<< [apiv2][body] GET https://cloudfunctions.googleapis.com/v2/projects/PROJECT_NAME/locations/asia-east1/operations/operation-1689073669967-600341c191066-017485c2-df7ba452 {"name":"projects/PROJECT_NAME/locations/asia-east1/operations/operation-1689073669967-600341c191066-017485c2-df7ba452","metadata":{"@type":"type.googleapis.com/google.cloud.functions.v2.OperationMetadata","createTime":"2023-07-11T11:07:50.417080718Z","target":"projects/PROJECT_NAME/locations/asia-east1/functions/ssrPROJECT_NAME","verb":"create","cancelRequested":false,"apiVersion":"v2","requestResource":{"@type":"type.googleapis.com/google.cloud.functions.v2.Function","name":"projects/PROJECT_NAME/locations/asia-east1/functions/ssrPROJECT_NAME","buildConfig":{"runtime":"nodejs18","entryPoint":"ssrPROJECT_NAME","source":{"storageSource":{"bucket":"gcf-v2-sources-105427367185-asia-east1","object":"ssrPROJECT_NAME/function-source.zip"}},"environmentVariables":{"GOOGLE_NODE_RUN_SCRIPTS":""}},"serviceConfig":{"service":"projects/PROJECT_NAME/locations/asia-east1/services/ssrPROJECT_NAME","timeoutSeconds":60," .. ..................... ,"availableMemory":"256Mi","maxInstanceRequestConcurrency":80,"availableCpu":"1"},"labels":{"deployment-tool":"cli-firebase","firebase-functions-codebase":"firebase-frameworks-PROJECT_NAME","firebase-functions-hash":""},"environment":"GEN_2"},"stages":[{"name":"BUILD","message":"Creating build","state":"IN_PROGRESS","resource":"projects/*******/locations/asia-east1/builds/","resourceUri":"https://console.cloud.google.com/cloud-build/builds;region=asia-east1/"},{"name":"SERVICE","state":"NOT_STARTED"}]},"done":false}
```

**Comment by Jonomyster** [comment]
I have also encountered this bug over the past few weeks. I'm not aware of any fix, but _right now_ I can reproduce it using the simplest possible SvelteKit demo app. Specifically:

```
yarn create vite
```
(Follow instructions to create a SvelteKit project.)
```
cd vite-project
npm install
firebase init
```
(Follow instructions to create a project with only hosting enabled, and connect it to a Firebase app on the Blaze plan.)
```
firebase deploy
```

I then encounter the exact same error:
```
i  functions: updating Node.js 18 (2nd Gen) function firebase-frameworks-cnktakw3yt32:ssrcnktakw3yt32(asia-east1)...
+  functions[firebase-frameworks-cnktakw3yt32:ssrcnktakw3yt32(asia-east1)] Successful update operation.
Function URL (firebase-frameworks-cnktakw3yt32:ssrcnktakw3yt32(asia-east1)): https://ssrcnktakw3yt32-ppxhazn7yq-de.a.run.app
i  functions: cleaning up build files...
i  hosting[cnktakw3yt32]: finalizing version...

Error: HTTP Error: 404, Requested entity was not found.
```

This error seems especially inconsistent to me. For instance, a couple of weeks ago I had the error on my main firebase project, but when I tried to reproduce (as above), it actually worked.

**Comment by AVancans** [comment]
I am facing the same problem with deploying the NextJS project. It seems it is not related to `firebase-tools` library directly and instead, there was some Google Cloud + Firebase Hosting integration change on their side.  The error started happening without any local config changes. Tried multiple `firebase-tools` versions, no luck. Tried creating a new hosting `profile/app`, and it's not able to even deploy the first deployment. The thing is, the deployment succeeds, it created a Cloud Run instance, but it creates an incorrect URL (not Firebase Hosting URL). Started happening a couple of days ago or so.

At this point, this is a critical outage from our side as we're not able to deploy any new updates via the current flow.

**Comment by t-k** [comment]
It seems that the behavior of the [updateVersion API ](https://github.com/firebase/firebase-tools/blob/f4581809c3af60fe58c10a143df0679f76d4b216/src/hosting/api.ts#L394-L415)has changed. It started returning 404 responses today.

**Comment by ClumsyBuddy** [comment]
Currently have the same issue when trying to deploy sveltekit.

**Comment by AVancans** [comment]
> It seems that the behavior of the [updateVersion API ](https://github.com/firebase/firebase-tools/blob/f4581809c3af60fe58c10a143df0679f76d4b216/src/hosting/api.ts#L394-L415)has changed. It started returning 404 responses today.

A quick hack for people with PRD impact while waiting for the proper fix:

1. Go to your `Cloud Run` service `YAML` section
2. Under ` traffic` copy and paste the tag value of the entry that's one before the last one. (For me it's the one above `  - percent: 100`
3.  Edit your `api.js` file of `firebase-tools`  (node_modules\firebase-tools\lib\hosting\api.js)

Find `updateVersion` method and hardcode the tag to one that you copied

Like that:
```
async function updateVersion(site, versionId, version) {
    version["config"]["rewrites"][0]["run"]["tag"] = "fh-bd0d4fbb2xxxxxxxxx";
    const res = await apiClient.patch(`projects/-/sites/${site}/versions/${versionId}`, version, {
        queryParams: {
            updateMask: proto.fieldMasks(version, "labels", "config").join(","),
        },
    });
    return res.body;
}
```

**Comment by aalej** [comment]
Hi @phminella, thanks for reporting this, and thanks to everyone for the additional context. I’m currently unable to reproduce this issue, but let me try to bring someone that can look into this and provide more context. 

To help us with our investigation, could you try running `firebase deploy --debug` and check if there is any http request resulting in a 404 before the error was raised. If so, could you share with us the debug logs starting from the failing request? This will help us verify what caused the issue. Please remove any PII (personal identifiable information).

**Comment by ClumsyBuddy** [comment]
It fails on finalizing version for hosting.
```
[2023-07-11T14:57:07.277Z] <<< [apiv2][status] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/rotmg-trade/versions/80b63ff8d33b7de1 404
[2023-07-11T14:57:07.277Z] <<< [apiv2][body] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/rotmg-trade/versions/80b63ff8d33b7de1 {"error":{"code":404,"message":"Requested entity was not found.","status":"NOT_FOUND"}}

Error: HTTP Error: 404, Requested entity was not found.
[2023-07-11T14:57:07.336Z] Error Context: {
  "body": {
    "error": {
      "code": 404,
      "message": "Requested entity was not found.",
      "status": "NOT_FOUND"
    }
  },
  "response": {
    "statusCode": 404
  }
}
```

**Comment by AVancans** [comment]
@aalej 

https://pastebin.com/0SSWUD7B

**Comment by Vochsel** [comment]
Also happening here... Incredibly frustrating having things _just break_...

**Comment by gustavopch** [comment]
It happened here 2 weeks ago, I contacted support and they told me they found the error and fixed. I didn't have to do anything here and it just started to work again. Today it started to happen again and I can't properly deploy:

<details>
  <summary>Logs</summary>

```sh
[2023-07-11T22:49:16.536Z] <<< [apiv2][status] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<omitted>/versions/1e55173d97491fdf 404
winston:file: written true false
[2023-07-11T22:49:16.537Z] <<< [apiv2][body] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<omitted>/versions/1e55173d97491fdf {"error":{"code":404,"message":"Requested entity was not found.","status":"NOT_FOUND"}}
winston:file: logged 273311 [debug] [2023-07-11T22:49:16.536Z] <<< [apiv2][status] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<omitted>/versions/1e55173d97491fdf 404

winston:file: logged 273568 [debug] [2023-07-11T22:49:16.537Z] <<< [apiv2][body] PATCH https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<omitted>/versions/1e55173d97491fdf {"error":{"code":404,"message":"Requested entity was not found.","status":"NOT_FOUND"}}

winston:file: written true false
[2023-07-11T22:49:16.704Z] <<< [apiv2][status] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<omitted>/channels/live/releases 200
winston:file: written true false
[2023-07-11T22:49:16.705Z] <<< [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<omitted>/channels/live/releases {"name":"projects/849887616585/sites/<omitted>/channels/live/releases/1689115756122000","version":{"name":"projects/849887616585/sites/<omitted>/versions/95dd8ccdb834b3d0","status":"FINALIZED","config":{"headers":[{"headers":{"cache-control":"public, max-age=86400"},"glob":"**/*.@(woff|woff2)"},{"headers":{"cache-control":"public, max-age=3600"},"glob":"**/*.@(gif|jpg|png|svg)"},{"headers":{"cache-control":"no-cache"},"glob":"**/*.@(html,css,js)"},{"headers":{"cache-control":"no-cache"},"glob":"/sw.js"}],"cleanUrls":true},"labels":{"deployment-tool":"cli-firebase"},"createTime":"2023-07-11T22:49:06.479403Z","createUser":{"email":"<omitted>","imageUrl":"<omitted>"},"finalizeTime":"2023-07-11T22:49:15.562211Z","finalizeUser":{"email":"<omitted>","imageUrl":"<omitted>"}},"type":"DEPLOY","releaseTime":"2023-07-11T22:49:16.122Z","message":"Test","releaseUser":{"email":"<omitted>","imageUrl":"<omitted>"}}
winston:file: written true false
[2023-07-11T22:49:16.706Z] [hosting] release: Test {"name":"projects/849887616585/sites/<omitted>/channels/live/releases/1689115756122000","version":{"name":"projects/849887616585/sites/<omitted>/versions/95dd8ccdb834b3d0","status":"FINALIZED","config":{"headers":[{"headers":{"cache-control":"public, max-age=86400"},"glob":"**/*.@(woff|woff2)"},{"headers":{"cache-control":"public, max-age=3600"},"glob":"**/*.@(gif|jpg|png|svg)"},{"headers":{"cache-control":"no-cache"},"glob":"**/*.@(html,css,js)"},{"headers":{"cache-control":"no-cache"},"glob":"/sw.js"}],"cleanUrls":true},"labels":{"deployment-tool":"cli-firebase"},"createTime":"2023-07-11T22:49:06.479403Z","createUser":{"email":"<omitted>","imageUrl":"<omitted>"},"finalizeTime":"2023-07-11T22:49:15.562211Z","finalizeUser":{"email":"<omitted>","imageUrl":"<omitted>"}},"type":"DEPLOY","releaseTime":"2023-07-11T22:49:16.122Z","message":"Test","releaseUser":{"email":"<omitted>","imageUrl":"<omitted>"}}
winston:file: written true false
✔  hosting[<omitted>]: release complete 
winston:file: logged 273733 [debug] [2023-07-11T22:49:16.704Z] <<< [apiv2][status] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<omitted>/channels/live/releases 200

winston:file: logged 275080 [debug] [2023-07-11T22:49:16.705Z] <<< [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/<omitted>/channels/live/releases {"name":"projects/849887616585/sites/<omitted>/channels/live/releases/1689115756122000","version":{"name":"projects/849887616585/sites/<omitted>/versions/95dd8ccdb834b3d0","status":"FINALIZED","config":{"headers":[{"headers":{"cache-control":"public, max-age=86400"},"glob":"**/*.@(woff|woff2)"},{"headers":{"cache-control":"public, max-age=3600"},"glob":"**/*.@(gif|jpg|png|svg)"},{"headers":{"cache-control":"no-cache"},"glob":"**/*.@(html,css,js)"},{"headers":{"cache-control":"no-cache"},"glob":"/sw.js"}],"cleanUrls":true},"labels":{"deployment-tool":"cli-firebase"},"createTime":"2023-07-11T22:49:06.479403Z","createUser":{"email":"<omitted>","imageUrl":"<omitted>"},"finalizeTime":"2023-07-11T22:49:15.562211Z","finalizeUser":{"email":"<omitted>","imageUrl":"<omitted>"}},"type":"DEPLOY","releaseTime":"2023-07-11T22:49:16.122Z","message":"Test","releaseUser":{"email":"<omitted>","imageUrl":"<omitted>"}}

winston:file: logged 276327 [debug] [2023-07-11T22:49:16.706Z] [hosting] release: Test {"name":"projects/849887616585/sites/<omitted>/channels/live/releases/1689115756122000","version":{"name":"projects/849887616585/sites/<omitted>/versions/95dd8ccdb834b3d0","status":"FINALIZED","config":{"headers":[{"headers":{"cache-control":"public, max-age=86400"},"glob":"**/*.@(woff|woff2)"},{"headers":{"cache-control":"public, max-age=3600"},"glob":"**/*.@(gif|jpg|png|svg)"},{"headers":{"cache-control":"no-cache"},"glob":"**/*.@(html,css,js)"},{"headers":{"cache-control":"no-cache"},"glob":"/sw.js"}],"cleanUrls":true},"labels":{"deployment-tool":"cli-firebase"},"createTime":"2023-07-11T22:49:06.479403Z","createUser":{"email":"<omitted>","imageUrl":"<omitted>"},"finalizeTime":"2023-07-11T22:49:15.562211Z","finalizeUser":{"email":"<omitted>","imageUrl":"<omitted>"}},"type":"DEPLOY","releaseTime":"2023-07-11T22:49:16.122Z","message":"Test","releaseUser":{"email":"<omitted>","imageUrl":"<omitted>"}}

winston:file: logged 276381 [info] ✔  hosting[<omitted>]: release complete 

winston:file: written true false

winston:file: written true false
Error: HTTP Error: 404, Requested entity was not found.
winston:file: written true false
[2023-07-11T22:49:16.712Z] Error Context: {
  "body": {
    "error": {
      "code": 404,
      "message": "Requested entity was not found.",
      "status": "NOT_FOUND"
    }
  },
  "response": {
    "statusCode": 404
  }
}
winston:file: logged 276390 [error] 

winston:file: logged 276454 [error] Error: HTTP Error: 404, Requested entity was not found.

winston:file: logged 276687 [debug] [2023-07-11T22:49:16.712Z] Error Context: {
  "body": {
    "error": {
      "code": 404,
      "message": "Requested entity was not found.",
      "status": "NOT_FOUND"
    }
  },
  "response": {
    "statusCode": 404
  }
}
```
</details>

**Comment by camstuart** [comment]
Same problem for me (on a sveltekit project) I have provided support with debug output from my deploy. `firebase deploy --debug` 

Just be carful sharing that file however, it contains your private key. I redacted mine before sharing with support.

**Comment by AxelRP** [comment]
Same for me with Angular Universal deployment. Yesterday evening deployment was working, this morning I got the 404 error

**Comment by aalej** [comment]
Hi everyone, sorry extra hoop here, but we would like to ask if anyone can share their `firebase-debug.log` and project ID to [Firebase Support](https://firebase.google.com/support). Our team has an idea of what might be causing this issue, but we would need to take a look into the project to verify.

Also, please mention this GitHub issue in the support ticket.

**Comment by phminella** [comment]
Hey, thanks aalej! Just in case no one has done it yet, I have shared my firebase-debug.log and project ID to firebase support. 

Case 10239154

**Comment by camstuart** [comment]
I also shared mine: case 10238751

**Comment by yoannmoinet** [comment]
Bringing my voice as well with case 10239195, sent my logs as well.
Hopefully they communicate on it at some point.
https://status.firebase.google.com/ doesn't show anything yet.

**Comment by al4nnw** [comment]
It started happening to me after updating the firebase-tools package. In my case, I'm trying to deploy an Next.js app and got the same errors.

**Comment by gabriellimoni** [comment]
> I am facing the same problem with deploying the NextJS project. It seems it is not related to `firebase-tools` library directly and instead, there was some Google Cloud + Firebase Hosting integration change on their side. The error started happening without any local config changes. Tried multiple `firebase-tools` versions, no luck. Tried creating a new hosting `profile/app`, and it's not able to even deploy the first deployment. The thing is, the deployment succeeds, it created a Cloud Run instance, but it creates an incorrect URL (not Firebase Hosting URL). Started happening a couple of days ago or so.
> 
> At this point, this is a critical outage from our side as we're not able to deploy any new updates via the current flow.

Same problem here with NextJS. Yesterday we did a couple of releases. Today we are not able to do it due this error.

**Comment by gustavopch** [comment]
> Hopefully they'll communicate on it at some point. It was a pain just to find this issue. https://status.firebase.google.com/ doesn't show anything yet.

Agreed. This issue should be in the status page, otherwise that page can't be trusted.

**Comment by inlined** [comment]
@AVancans Be careful; your fix will cause deploys of previews to modify production.

**Comment by vDeo-TS** [comment]
Also getting this error when trying to deploy the our team's NextJS app.

**Comment by inlined** [comment]
*Update*: We think there is a server-side error. We are investigating and addressing this. This is an error that affects users using the `pinTags` feature, which includes all web frameworks users while the feature is available.

Fortunately, `pintags` is still an experiment and can be disabled without downgrading your CLI. If you turn off this experiment, you'll lose atomic rollbacks and preview channels with server-side content, but you'll be able to deploy to production again while we figure this out. To disable the experiment, run:

```
firebase experiments:disable pintags
```

You will permanently lose the feature until we either remove the experiment guard or until you reenable the feature with

```
firebase experiments:enable pintags
```

**Comment by VVIERV00** [comment]
I'm encountering an issue with Firebase deployment. Instead of deploying to Firebase Hosting as expected, the deployment ends up on Google Cloud Run with a randomly named URL.

Here is the error message I'm receiving:
`Function URL (firebase-frameworks-XXXX:XXXX(europe-west1)): https://XXXXX-XXX-ew.a.run.app
i  functions: cleaning up build files...
i  hosting[apuntalo-ec9c1]: finalizing version...
Error: HTTP Error: 404, Requested entity was not found.
`
In my case, this is my first time deploying my Next.js app to Firebase. Initially, I thought the problem was on my end until I came across this issue.

**Comment by inlined** [comment]
@VVIERV00 Web Frameworks uses Cloud Functions 2nd Generation, which uses Cloud Run as its runtime. The Cloud Run URL is expected, though your application will also/instead use your Hosting URL for the full stack experience.

**Comment by VVIERV00** [comment]
@inlined, thank you for the clarification. I'm looking forward to seeing the issue addressed. Please feel free to let me know if there's any information or assistance I can provide to help resolve this issue.

**Comment by camstuart** [comment]
Thanks 

> _Update_: We think there is a server-side error. We are investigating and addressing this. This is an error that affects users using the `pinTags` feature, which includes all web frameworks users while the feature is available.
> 
> Fortunately, `pintags` is still an experiment and can be disabled without downgrading your CLI. If you turn off this experiment, you'll lose atomic rollbacks and preview channels with server-side content, but you'll be able to deploy to production again while we figure this out. To disable the experiment, run:
> 
> ```
> firebase experiments:disable pintags
> ```
> 
> You will permanently lose the feature until we either remove the experiment guard or until you reenable the feature with
> 
> ```
> firebase experiments:enable pintags
> ```

Thanks for this, deploy worked for me after disabling pintags. I noticed as well that the firebase tools just had a new release: `Update available 12.4.3 → 12.4.4` does that include a fix. or is it an unrelated update?

**Comment by inlined** [comment]
It was an unrelated update. There was a bad server-side update in Cloud Run that affected tagged URLs. The change has been rolled back and you should be able to reenable pintags. Note that you will need to push to production with pintags enabled before you can create a new preview with pintags (otherwise the preview would modify prod).

**Comment by Alab1** [comment]
seems solved now ... at least from my side.
have a great day guys

**Comment by phminella** [comment]
Same here. Thank you!

**Comment by GavinSalcedo** [comment]
Looks like Firebase hosting is stable again. 

I can confirm we're able to proceed with the deployment. Thanks!

**Comment by VVIERV00** [comment]
I'm still encountering issues with successfully deploying my app, and I suspect it might be related to the following: the dynamic routes in Next.js are functioning only on the Cloud Run link produced by the deploy command:

`Function URL (firebase-frameworks-xx-x:xxx(europe-west1)): https://xxx-xxxx-ew.a.run.app
`
However, they are not working on the hosting web.app / custom domain. I tried re-enabling pintags, which no longer show error messages, yet the issue with dynamic routes persists.

I suspect the problem might lie with accessing the Cloud Function executing dynamic routes. This function shares the same name, ssrapuntXXX, as the Cloud Run. Somehow the main hosting domain can't access it, I can't find any help on the docs.

**Comment by chrisryanouellette** [comment]
Hey all! I ran into this with a new project without any deploy. 
Firebase: 10.6.0
Firebase Tools: 12.9.1
Node: 18
NextJS: 13.4.5

I also submitted a bug ticket with Firebase.

```
[debug] [2023-11-29T16:50:41.628Z] <<< [apiv2][status] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/[Site Name]/versions 404
[debug] [2023-11-29T16:50:41.628Z] <<< [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/[Site Name]/versions {"error":{"code":404,"message":"Requested entity was not found.","status":"NOT_FOUND"}}
[error] 
[error] Error: HTTP Error: 404, Requested entity was not found.
[debug] [2023-11-29T16:50:41.779Z] Error Context: {
  "body": {
    "error": {
      "code": 404,
      "message": "Requested entity was not found.",
      "status": "NOT_FOUND"
    }
  },
  "response": {
    "statusCode": 404
  }
}
```

**Comment by cadepeters43** [comment]
I am encountering this issue. Anyone else?

**Comment by baptistelladev** [comment]
me 

> I am encountering this issue. Anyone else?

**Comment by spock123** [comment]
Hi, we are now getting this while setting up a new project app. We have several other apps configured, but this one gives the dreaded error:

Debug log:
```

[2025-06-06T08:25:23.172Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2025-06-06T08:25:23.173Z] > authorizing via signed-in user (lars.jeppesen@gmail.com)
[2025-06-06T08:25:23.173Z] [iam] checking project fastorder-demo for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[2025-06-06T08:25:23.173Z] Checked if tokens are valid: true, expires at: 1749201488269
[2025-06-06T08:25:23.173Z] Checked if tokens are valid: true, expires at: 1749201488269
[2025-06-06T08:25:23.173Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/fastorder-demo:testIamPermissions [none]
[2025-06-06T08:25:23.173Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/fastorder-demo:testIamPermissions x-goog-quota-user=projects/fastorder-demo
[2025-06-06T08:25:23.174Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/fastorder-demo:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[2025-06-06T08:25:24.261Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/fastorder-demo:testIamPermissions 200
[2025-06-06T08:25:24.262Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/fastorder-demo:testIamPermissions {"permissions":["firebase.projects.get","firebasehosting.sites.update"]}
[2025-06-06T08:25:24.262Z] Checked if tokens are valid: true, expires at: 1749201488269
[2025-06-06T08:25:24.262Z] Checked if tokens are valid: true, expires at: 1749201488269
[2025-06-06T08:25:24.263Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/fastorder-demo [none]
[2025-06-06T08:25:24.769Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/fastorder-demo 200
[2025-06-06T08:25:24.770Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/fastorder-demo {"projectId":"fastorder-demo","projectNumber":"131029190576","displayName":"fastorder-demo","name":"projects/fastorder-demo","resources":{"hostingSite":"fastorder-demo"},"state":"ACTIVE","etag":"1_fe6f6b01-d682-43d7-a34d-48cba0c889b9"}

=== Deploying to 'fastorder-demo'...

i  deploying hosting
[2025-06-06T08:25:24.776Z] Checked if tokens are valid: true, expires at: 1749201488269
[2025-06-06T08:25:24.776Z] Checked if tokens are valid: true, expires at: 1749201488269
[2025-06-06T08:25:24.776Z] >>> [apiv2][query] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/fresto-demo-analytics/versions [none]
[2025-06-06T08:25:24.776Z] >>> [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/fresto-demo-analytics/versions {"status":"CREATED","labels":{"deployment-tool":"cli-firebase"}}
[2025-06-06T08:25:25.880Z] <<< [apiv2][status] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/fresto-demo-analytics/versions 404
[2025-06-06T08:25:25.880Z] <<< [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/fresto-demo-analytics/versions {"error":{"code":404,"message":"Requested entity was not found.","status":"NOT_FOUND"}}

Error: Request to https://firebasehosting.googleapis.com/v1beta1/projects/-/sites/fresto-demo-analytics/versions had HTTP Error: 404, Requested entity was not found.
[2025-06-06T08:25:25.952Z] Error Context: {
  "body": {
    "error": {
      "code": 404,
      "message": "Requested entity was not found.",
      "status": "NOT_FOUND"
    }
  },
  "response": {
    "statusCode": 404
  }
}
```

**Comment by marcosb** [comment]
In my case (I had the same error), it was because my cloud run service did not have "Default HTTPS endpoint URL" checked/enabled.  It can be found under "Networking" in service details.

It sure would be nice if the error was a bit more precise, i.e. "Requested entity was not found" is not very useful.
