### ISSUE TITLE
Storage rules deployment suddenly stopped working

### ISSUE THREAD

**Issue by Burgov** [firebase/firebase-tools#6567]
### [REQUIRED] Environment info

**firebase-tools:** 12.8.1

**Platform:** various

### [REQUIRED] Test case

Unable to reproduce in a clean environment

### [REQUIRED] Steps to reproduce

Run firebase deploy --only storage

### [REQUIRED] Expected behavior

It deploys the storage rules

### [REQUIRED] Actual behavior

```
[2023-12-04T20:09:56.726Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[2023-12-04T20:09:56.727Z] > authorizing via signed-in user (bart@salesbuildr.com)
[2023-12-04T20:09:56.727Z] [iam] checking project msp-navigator-dev-3c0ae for permissions ["firebase.projects.get","firebaserules.releases.create","firebaserules.releases.update","firebaserules.rulesets.create"]
[2023-12-04T20:09:56.728Z] > refreshing access token with scopes: []
[2023-12-04T20:09:56.729Z] >>> [apiv2][query] POST https://www.googleapis.com/oauth2/v3/token [none]
[2023-12-04T20:09:56.729Z] >>> [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[2023-12-04T20:09:56.845Z] <<< [apiv2][status] POST https://www.googleapis.com/oauth2/v3/token 200
[2023-12-04T20:09:56.845Z] <<< [apiv2][body] POST https://www.googleapis.com/oauth2/v3/token [omitted]
[2023-12-04T20:09:56.885Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/msp-navigator-dev-3c0ae:testIamPermissions [none]
[2023-12-04T20:09:56.885Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/msp-navigator-dev-3c0ae:testIamPermissions x-goog-quota-user=projects/msp-navigator-dev-3c0ae
[2023-12-04T20:09:56.885Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/msp-navigator-dev-3c0ae:testIamPermissions {"permissions":["firebase.projects.get","firebaserules.releases.create","firebaserules.releases.update","firebaserules.rulesets.create"]}
[2023-12-04T20:09:57.072Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/msp-navigator-dev-3c0ae:testIamPermissions 200
[2023-12-04T20:09:57.072Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/msp-navigator-dev-3c0ae:testIamPermissions {"permissions":["firebase.projects.get","firebaserules.releases.create","firebaserules.releases.update","firebaserules.rulesets.create"]}

=== Deploying to 'msp-navigator-dev-3c0ae'...

i  deploying storage 
Running command: npm run generate-storage-rules

> msp-navigator@0.0.0 generate-storage-rules
> node dist/apps/firestore-rules/main.js storage

✔  storage: Finished running predeploy script. 
[2023-12-04T20:09:57.377Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/msp-navigator-dev-3c0ae [none]
[2023-12-04T20:09:57.801Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/msp-navigator-dev-3c0ae 200
[2023-12-04T20:09:57.801Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/msp-navigator-dev-3c0ae {"projectId":"msp-navigator-dev-3c0ae","projectNumber":"284821635234","displayName":"MSP Navigator Dev","name":"projects/msp-navigator-dev-3c0ae","resources":{"hostingSite":"msp-navigator-dev-3c0ae","realtimeDatabaseInstance":"msp-navigator-dev-3c0ae","locationId":"europe-west"},"state":"ACTIVE","etag":"1_6170cb48-bee6-45f8-bfd1-c4dbd2ecc68f"}
[2023-12-04T20:09:57.802Z] Default storage bucket is undefined.


There was an issue deploying your functions. Verify that your project has a Google App Engine instance setup at https://console.cloud.google.com/appengine and try again. If this issue persists, please contact support.

Error: Your project is being set up. Please wait a minute before deploying again.
```

This problem started occurring for two projects at the same time. I've checked App Engine, it clearly states a default storage bucket is selected. I checked in the code and it's expecting a key `storageBucket` in the `resources` object from the logs above, just before the error, but as you can see, it is not there.

Did anything change that could cause this to happen? I tried upgrading firebase-tools to the latest but it didn't have an effect.

**Comment by jeffgaynor** [comment]
I can confirm this exact bug started today, and I also didn't change anything, like @Burgov, with `firebase-tools@^12.9.1`. It was working last night, no changes, and now it doesn't.

**Comment by MeTaNoV** [comment]
same here, it was working 7 hours ago...

**Comment by cedvdb** [comment]
Started happening today in CI, v`12.9.1`.

We have a firebase project, never actually entered the app engine panel and there does not seem to be a configuration there.

![image](https://github.com/firebase/firebase-tools/assets/22280985/31e6f9d0-d327-46b5-ab74-8d5dd95f882c)

**Comment by Burgov** [comment]
@cedvdb in App Engine Console, go to Settings. It should say sth like this there:

<img width="542" alt="Screenshot 2023-12-04 at 23 26 31" src="https://github.com/firebase/firebase-tools/assets/417674/e3772beb-8c35-485b-b920-c63c92d5b8b5">

This confirms that despite the error message, there is in fact a default Cloud Storage bucket.

**Comment by TangrisJones** [comment]
I can confirm this is happening to me as well!

**Comment by jeffgaynor** [comment]
Since it was working for all of us yesterday / several hours ago, and different firebase-tools versions are experiencing the same issue, it may be due to this GCP incident: https://status.cloud.google.com/incidents/3CMcRiqNus4M1xFysuvw#RP1d9aZLNFZEJmTBk8e1

**Comment by SveBo** [comment]
Same happening here

**Comment by yshirsath** [comment]
May be related to: https://github.com/firebase/firebase-tools/issues/6162

Temporary fix: Downgrading firebase-tools to `11.22.0` (or any version that uses the `http://appengine.googleapis.com/` api rather than the `http://firebase.googleapis.com/` api to fetch the default storage bucket) worked for us

**Comment by macksal** [comment]
I'm also experiencing this. Downgrading to `11.30.0` worked for me.

Did a broken version of the `http://firebase.googleapis.com/` get deployed somehow...?

**Comment by SergeiEensalu** [comment]
Faced into the same problem :)

**Comment by aalej** [comment]
Hey everyone, thanks for raising this and apologies for the issue this has caused. I’ve notified our team so that they can investigate what is causing this. I tried deploying using different versions of the Firebase CLI, and from what I can tell using v12.3.1 works.

**Comment by omgovich** [comment]
We are having the same issue. Our deployment script just stopped working today.

**Comment by anandsathe67** [comment]
Same issue - wasted a few hours trying to figure it out. @aalej - could you also please request the fixer to change the error message ? Talk about completely confusing the user  with these current messages:
> project being set up ? Wait for a minute before deploying again (?)
> Verify that your project has a Google App Engine instance setup at https://console.cloud.google.com/appengine and try again (???)
You can imagine the wild goose chase such messages put us through. 

From src/gcp/storage.ts
   ```
export async function getDefaultBucket(projectId: string): Promise<string> {
  try {
    const metadata = await getFirebaseProject(projectId);
    if (!metadata.resources?.storageBucket) {
      logger.debug("Default storage bucket is undefined.");
      throw new FirebaseError(
        "Your project is being set up. Please wait a minute before deploying again."
      );
    }
    return metadata.resources.storageBucket;
  } catch (err: any) {
    logger.info(
      "\n\nThere was an issue deploying your functions. Verify that your project has a Google App Engine instance setup at https://console.cloud.google.com/appengine and try again. If this issue persists, please contact support."
    );
    throw err;
  }
}
```

**Comment by smallTrogdor** [comment]
Having the same problem since tonight, being on an europe-west3 resource location.
Using **firebase-tools 12.9.1**

I get the error 

```
i  deploying storage, firestore, functions

There was an issue deploying your functions. Verify that your project has a Google App Engine instance setup at https://console.cloud.google.com/appengine and try again. If this issue persists, please contact support.

Error: Your project is being set up. Please wait a minute before deploying again.
```

**Comment by stellageo** [comment]
Same issue also since 4/12. 
Any attempt for full deploy fails. 

Managed to deploy each part using "--only", but it takes about 10 tries until succeed. 
Error messages are mentioned above.

**Comment by anandsathe67** [comment]
One workaround (assuming your storage rules are stable and not being changed) is to run 
firebase deploy ...  --except storage
@aalej  - could you please confirm that all storage deployment does is compile storage rules and it is safe to skip this if the rules haven't changed? Thank you

**Comment by aalej** [comment]
Hey everyone, sorry for the delayed updates here. Our team looked into this issue and rolled out a fix. Can anyone try deploying their storage rules via `firebase deploy --only storage` to see if you’d still encounter any errors? I tried it out using v12.9.1 no errors are being raised.

@anandsathe67, skipping Storage rules deployments should be fine. This should deploy your code and assets without modifying your Storage rules.

**Comment by Jpoliachik** [comment]
Worked on my end! Thanks @aalej

**Comment by omgovich** [comment]
I can confirm that the issue is fixed — we were able to deploy the app.
@aalej thanks for making the fix live so fast!

**Comment by joehan** [comment]
Closing this since the issue has been resolved - thanks @aalej!

**Comment by stellageo** [comment]
with firebase deploy --except storage
i got 
Error: Failed to make request to https://firestore.googleapis.com/v1/projects/...../databases/(default)/collectionGroups/-/fields?filter=indexConfig.usesAncestorConfig=false OR ttlConfig:*
and 
Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.

**Comment by joehan** [comment]
@stellageo Those errors seem like separate issues - if you are still having trouble, could you open a different issue for those with full details?

**Comment by stellageo** [comment]
@joehan  I'll try again and if  i still have errors, I'll open a new issue. thanks.

**Comment by mazenkhalil** [comment]
Anyone still experiencing this issue? I have got this resolved on one project but the other project still facing the same error!

**Comment by mazenkhalil** [comment]
I think the problem still affecting newly created projects. The project having the issue has been created yesterday.

**Comment by johnnyoshika** [comment]
Running `firebase deploy --only functions,firestore:rules,firestore:indexes,storage` still doesn't deploy firebase.rules even though it compiles property (according to this terminal message):

![image](https://github.com/firebase/firebase-tools/assets/504505/57d14d33-9254-4696-a2be-fb6e8f8cb62b)

I'm using `firebase-tools@12.9.1`. I'll try upgrading to v13+ to see if it solves it.

**Comment by macksal** [comment]
> I upgraded my GitHub Actions to use `firebase-tools@13.4.0` but firestore rules still don't deploy. Strangely it seems to deploy fine when I run `firebase deploy --only firestore:rules` directly from my local Windows machine. Bizarre!

You may want to check what roles are assigned to the service account key used in your CI. I'm assuming you're not using this service account locally, so it's possible that it's missing some permissions. You could confirm by using the same service account key on your local machine.

Unfortunately I don't have a list of all the permissions required, but you could search for it.

You can also get more diagnostic information by running `firebase deploy` with the `--debug` flag in CI. It will tell you which API calls are actually failing if any.

**Comment by johnnyoshika** [comment]
Figured it out. This won't deploy changes to firestore.rules:

```
firebase deploy --only 'firestore:rules,firestore:indexes' --project {project_id}
```

This will:

```
firebase deploy --only 'firestore:rules' --project examind-dev
```

I filed a [bug here](https://github.com/firebase/firebase-tools/issues/6857).
