### ISSUE TITLE
Can't deploy Cloud Functions: "Cloud Runtime Config is currently experiencing issues"

### ISSUE THREAD

**Issue by risalfajar** [firebase/firebase-tools#8117]
### [REQUIRED] Environment info

**firebase-tools:** 13.29.1

**Platform:** MacOs Sonoma

### [REQUIRED] Test case

I think this is just a regression of #7341 , but this time, the problem is from the network. I can only deploy my functions when connecting to my phone's hotspot.

### [REQUIRED] Steps to reproduce

1. Connect to your home wifi
2. Deploy functions

### [REQUIRED] Expected behavior

It should work

### [REQUIRED] Actual behavior

```sh
✔  functions: Finished running predeploy script.
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled

Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.
```

**Comment by aalej** [comment]
Hey @risalfajar, sorry to hear you encountered this issue. I'm trying to reproduce this but so far no errors are being raised when deploying functions. I've also asked some colleagues to try deploying on their end and they’re also able to deploy successfully.

At the moment, it's hard to determine what’s causing this issue. My best guess is that there might be something in your network that is preventing or blocking the call to Cloud Runtime Config. Could you share your `firebase-debug.log` so that we can check what’s causing this error?

**Comment by ivoneug** [comment]
@aalej hi there. I'm experiencing the same issue as the topic starter. Seems like it's not related to network type (tried via home wifi network and cellular).
Looks like it is the issue with firebase config endpoint that responds with 500 error code.

If you do "firebase functions:config:get" then it responds with the following message:
Error: Request to https://runtimeconfig.googleapis.com/v1beta1/projects/sandbox-5f640/configs had HTTP Error: 500, Internal error encountered.

**Comment by Zloka** [comment]
Hi

I'm not the original author, but I started experiencing the same issue this morning. I deployed cloud functions to this project just fine yesterday afternoon.

```
eploying functions
i  functions: preparing codebase default for deployment
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled

Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.
```

Some people in this issue (https://github.com/firebase/firebase-tools/issues/7341) mentioned a VPN working, but that does not seem to work for me. Neither a VPN nor a different network made a difference.

Here are the contents of `firebase-debug.log` after running `firebase deploy --only functions:<single-function-name> --debug`

```
[debug] [2025-01-17T08:21:28.109Z] ----------------------------------------------------------------------
[debug] [2025-01-17T08:21:28.111Z] Command:       /Users/<username-masked>/.nvm/versions/node/v20.5.0/bin/node /Users/<username-masked>/.nvm/versions/node/v20.5.0/bin/firebase deploy --only functions:onMaterialChaptersCreated --debug
[debug] [2025-01-17T08:21:28.111Z] CLI Version:   13.11.4
[debug] [2025-01-17T08:21:28.111Z] Platform:      darwin
[debug] [2025-01-17T08:21:28.111Z] Node Version:  v20.5.0
[debug] [2025-01-17T08:21:28.111Z] Time:          Fri Jan 17 2025 10:21:28 GMT+0200 (Eastern European Standard Time)
[debug] [2025-01-17T08:21:28.111Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-01-17T08:21:28.146Z] Field ".storage" in "firebase.json" is possibly invalid: should be object
[debug] [2025-01-17T08:21:28.147Z] Object ".storage[0]" in "firebase.json" is missing required property: {"missingProperty":"bucket"}
[debug] [2025-01-17T08:21:28.147Z] Field ".storage" in "firebase.json" is possibly invalid: should match some schema in anyOf
[debug] [2025-01-17T08:21:28.149Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2025-01-17T08:21:28.150Z] > authorizing via signed-in user (<username-masked>)
[debug] [2025-01-17T08:21:28.150Z] [iam] checking project <project-id-masked>-production for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]
[debug] [2025-01-17T08:21:28.151Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/<project-id-masked>-production:testIamPermissions [none]
[debug] [2025-01-17T08:21:28.151Z] >>> [apiv2][(partial)header] POST https://cloudresourcemanager.googleapis.com/v1/projects/<project-id-masked>-production:testIamPermissions x-goog-quota-user=projects/<project-id-masked>-production
[debug] [2025-01-17T08:21:28.151Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/<project-id-masked>-production:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]}
[debug] [2025-01-17T08:21:28.960Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/<project-id-masked>-production:testIamPermissions 200
[debug] [2025-01-17T08:21:28.961Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/<project-id-masked>-production:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get"]}
[debug] [2025-01-17T08:21:28.961Z] >>> [apiv2][query] POST https://iam.googleapis.com/v1/projects/<project-id-masked>-production/serviceAccounts/<project-id-masked>-production@appspot.gserviceaccount.com:testIamPermissions [none]
[debug] [2025-01-17T08:21:28.961Z] >>> [apiv2][body] POST https://iam.googleapis.com/v1/projects/<project-id-masked>-production/serviceAccounts/<project-id-masked>-production@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[debug] [2025-01-17T08:21:29.757Z] <<< [apiv2][status] POST https://iam.googleapis.com/v1/projects/<project-id-masked>-production/serviceAccounts/<project-id-masked>-production@appspot.gserviceaccount.com:testIamPermissions 200
[debug] [2025-01-17T08:21:29.757Z] <<< [apiv2][body] POST https://iam.googleapis.com/v1/projects/<project-id-masked>-production/serviceAccounts/<project-id-masked>-production@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[info] 
[info] === Deploying to '<project-id-masked>-production'...
[info] 
[info] i  deploying functions 
[debug] [2025-01-17T08:21:29.760Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/<project-id-masked>-production [none]
[debug] [2025-01-17T08:21:30.022Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/<project-id-masked>-production 200
[debug] [2025-01-17T08:21:30.022Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/<project-id-masked>-production {"projectId":"<project-id-masked>-production","projectNumber":"478053187810","displayName":"<project-id-masked> Production","name":"projects/<project-id-masked>-production","resources":{"hostingSite":"<project-id-masked>-production","realtimeDatabaseInstance":"<project-id-masked>-production","storageBucket":"<project-id-masked>-production.appspot.com","locationId":"europe-west"},"state":"ACTIVE","etag":"1_fdd21fd9-4abd-42da-8751-eff2cd0f469e"}
[info] i  functions: preparing codebase default for deployment 
[info] i  functions: ensuring required API cloudfunctions.googleapis.com is enabled... 
[info] i  functions: ensuring required API cloudbuild.googleapis.com is enabled... 
[info] i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled... 
[debug] [2025-01-17T08:21:30.023Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/cloudfunctions.googleapis.com [none]
[debug] [2025-01-17T08:21:30.023Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/cloudfunctions.googleapis.com x-goog-quota-user=projects/<project-id-masked>-production
[debug] [2025-01-17T08:21:30.024Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/runtimeconfig.googleapis.com [none]
[debug] [2025-01-17T08:21:30.024Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/runtimeconfig.googleapis.com x-goog-quota-user=projects/<project-id-masked>-production
[debug] [2025-01-17T08:21:30.025Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/cloudbuild.googleapis.com [none]
[debug] [2025-01-17T08:21:30.025Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/cloudbuild.googleapis.com x-goog-quota-user=projects/<project-id-masked>-production
[debug] [2025-01-17T08:21:30.025Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/artifactregistry.googleapis.com [none]
[debug] [2025-01-17T08:21:30.025Z] >>> [apiv2][(partial)header] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/artifactregistry.googleapis.com x-goog-quota-user=projects/<project-id-masked>-production
[debug] [2025-01-17T08:21:30.974Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/artifactregistry.googleapis.com 200
[debug] [2025-01-17T08:21:30.974Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/artifactregistry.googleapis.com [omitted]
[info] ✔  artifactregistry: required API artifactregistry.googleapis.com is enabled 
[debug] [2025-01-17T08:21:30.980Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/cloudbuild.googleapis.com 200
[debug] [2025-01-17T08:21:30.980Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/cloudbuild.googleapis.com [omitted]
[info] ✔  functions: required API cloudbuild.googleapis.com is enabled 
[debug] [2025-01-17T08:21:30.998Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/cloudfunctions.googleapis.com 200
[debug] [2025-01-17T08:21:30.998Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/cloudfunctions.googleapis.com [omitted]
[info] ✔  functions: required API cloudfunctions.googleapis.com is enabled 
[debug] [2025-01-17T08:21:31.028Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/runtimeconfig.googleapis.com 200
[debug] [2025-01-17T08:21:31.028Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/<project-id-masked>-production/services/runtimeconfig.googleapis.com [omitted]
[debug] [2025-01-17T08:21:31.029Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/<project-id-masked>-production/adminSdkConfig [none]
[debug] [2025-01-17T08:21:31.571Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/<project-id-masked>-production/adminSdkConfig 200
[debug] [2025-01-17T08:21:31.571Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/<project-id-masked>-production/adminSdkConfig {"projectId":"<project-id-masked>-production","databaseURL":"https://<project-id-masked>-production.firebaseio.com","storageBucket":"<project-id-masked>-production.appspot.com","locationId":"europe-west"}
[debug] [2025-01-17T08:21:31.572Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/<project-id-masked>-production/configs [none]
[debug] [2025-01-17T08:21:32.430Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/<project-id-masked>-production/configs 500
[debug] [2025-01-17T08:21:32.430Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/<project-id-masked>-production/configs {"error":{"code":500,"message":"Internal error encountered.","status":"INTERNAL"}}
[debug] [2025-01-17T08:21:33.432Z] *** [apiv2] Attempting the request again. Attempt number 2
[debug] [2025-01-17T08:21:33.433Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/<project-id-masked>-production/configs [none]
[debug] [2025-01-17T08:21:34.206Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/<project-id-masked>-production/configs 500
[debug] [2025-01-17T08:21:34.207Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/<project-id-masked>-production/configs {"error":{"code":500,"message":"Internal error encountered.","status":"INTERNAL"}}
[debug] HTTP Error: 500, Internal error encountered.
[error] 
[error] Error: Cloud Runtime Config is currently experiencing issues, which is preventing your functions from being deployed. Please wait a few minutes and then try to deploy your functions again.
Run `firebase deploy --except functions` if you want to continue deploying the rest of your project.
```

Just like @ivoneug, if I run `firebase functions:config:get`, I too get the response `Error: HTTP Error: 500, Internal error encountered.`.

**Comment by manojsachwani** [comment]
Same... was working fine a few hours ago and now this. Tried changing regions via VPN, etc. No go.

On `firebase functions:config:get`
Getting this:
`Request to https://runtimeconfig.googleapis.com/v1beta1/projects/ez4cast/configs had HTTP Error: 500, Internal error encountered.`

**Comment by fobin** [comment]
Same issue here. Status board doesn't say there is an issue going on.

**Comment by miodrage** [comment]
+1

**Comment by henry798798** [comment]
+1

**Comment by big-brave-pete** [comment]
+1 Seeing the same issue

**Comment by SimonDar** [comment]
+1

**Comment by mcanyucel** [comment]
+1. I was able to deploy functions yesterday but today in the morning it is broken. Feels like a service outage.

**Comment by desk-pro** [comment]
+1

**Comment by g1henx** [comment]
+ 1

**Comment by SimonDar** [comment]
Looks fixed now :)

**Comment by aalej** [comment]
Hey folks, I'm trying to reproduce this again and currently deploying functions raises no errors. As mentioned in https://github.com/firebase/firebase-tools/issues/8117#issuecomment-2597794716 it looks the issue may have been resolved, could anyone also try deploying their functions to see if any errors would still occur?

**Comment by fobin** [comment]
Works now

**Comment by manojsachwani** [comment]
Works great. Thanks
