### ISSUE TITLE
Webframeworks project deployment fails on v14

### ISSUE THREAD

**Issue by nvzoll** [firebase/firebase-tools#8378]
### [REQUIRED] Environment info

**firebase-tools:** v14.0.0

**Platform:** ubuntu (github action)

### [REQUIRED] Test case

`npx firebase-tools@latest hosting:channel:deploy <channel> --only production --expires 7d --project <my-gcloud-project> --json`
or
`npx firebase-tools@latest deploy --only hosting:production --project <my-gcloud-project> --json`

### [REQUIRED] Steps to reproduce

1. Next.js 15 project, pages router, use the command above

### [REQUIRED] Expected behavior

Project deploys (still happens with v13.35.1)

### [REQUIRED] Actual behavior

Initial run:
```
functions: No cleanup policy detected for repositories in us-central1. This may result in a small monthly bill as container images accumulate over time. 
  
  Error: Functions successfully deployed but could not set up cleanup policy in location us-central1. Pass the --force option to automatically set up a cleanup policy or run 'firebase functions:artifacts:setpolicy' to manually set up a cleanup policy.
```

After adjusting the settings:
```
[2025-03-27T20:18:38.469Z] Functions deploy failed.
  [2025-03-27T20:18:38.470Z] ***
  [2025-03-27T20:18:38.470Z] TypeError: Cannot read properties of null (reading 'length')
      at Object.formatServiceAccount (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/firebase-tools/lib/gcp/proto.js:95:24)
      at /home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/firebase-tools/lib/gcp/cloudfunctionsv2.js:196:122
      at Object.convertIfPresent (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/firebase-tools/lib/gcp/proto.js:45:25)
      at Object.functionFromEndpoint (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/firebase-tools/lib/gcp/cloudfunctionsv2.js:196:11)
      at Fabricator.updateV2Function (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:384:35)
      at Fabricator.updateEndpoint (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:155:24)
      at /home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:110:71
      at handle (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:89:23)
      at Fabricator.applyChangeset (/home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:110:26)
      at /home/runner/.npm/_npx/ba4f1959e38407b5/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:69:40
  
  Error: There was an error deploying functions
  
  The process '/usr/local/bin/npx' failed with exit code 2
```

**Comment by nvzoll** [comment]
Github action: `FirebaseExtended/action-hosting-deploy@v0`

**Comment by LucianoGanga** [comment]
Hello! I'm having the exact same issue. And I imagine a lot more people will have it soon. By default my deploy script installs the latest firebase-tool package. I was fighting for the last 2 and a half hours with our code until I saw that the version 14 of this package was published ~3h ago. 

The only breaking change I see in the release notes, related to cloud functions is this:
> BREAKING(cloud functions)! Removed the experimental:functions:shell command. Use functions:shell instead.
so I don't understand what happened, because we're not using that command. 


Anyhow, the fix that worked for us: 
```
npm install -g firebase-tools@13 
```


Thanks!

**Comment by OutdatedGuy** [comment]
<img width="1274" alt="Image" src="https://github.com/user-attachments/assets/454f8b5d-c87f-4530-ac2c-9bc0f81ef350" />

I think the issue related to the above warning we used to get in `firebase-tools@13`. [For more informations](https://cloud.google.com/docs/authentication/getting-started).

**Comment by nvzoll** [comment]
@OutdatedGuy actually, `FirebaseExtended/action-hosting-deploy@v0` I referred above does use `GOOGLE_APPLICATION_CREDENTIALS`
https://github.com/FirebaseExtended/action-hosting-deploy/blob/main/src/deploy.ts#L102

**Comment by OutdatedGuy** [comment]
Can you give details about how your `FirebaseExtended/action-hosting-deploy@v0` step is configured for actions?

**Comment by nvzoll** [comment]
Sure
```
- run: |
                  export NODE_OPTIONS=--max_old_space_size=4096
                  npm ci && npm run build
            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: '${{ secrets.GITHUB_TOKEN }}'
                  firebaseServiceAccount: '${{ secrets.<service account json content>}}'
                  channelId: live
                  projectId: <my-project>
                  target: production
              env:
                  FIREBASE_CLI_EXPERIMENTS: webframeworks
```

**Comment by haggbart** [comment]
I'm experiencing the exact same issue with Firebase CLI v14.0.0. The error occurs even on a fresh project

**Comment by sufyankhatri** [comment]
I'm experiencing the exact same issue with Firebase CLI v14.0.0. The error occurs even on a fresh project

**Comment by service-paradis** [comment]
I though I was crazy! Similar problems here with `FirebaseExtended/action-hosting-deploy@v0.9.0` which installed `firebase-tools@14.0.0`

**Comment by ph360** [comment]
![Image](https://github.com/user-attachments/assets/ec0bdebb-5b14-470b-b70f-a0fb26a4e675) 

When I deploy my functions since github show me the same error.

**Comment by redian** [comment]
If you are using `FirebaseExtended/action-hosting-deploy@v0` action and facing this issue, you can force firebase-tools version using the `firebaseToolsVersion` config on the GA job.

Something like this would work:

```
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
        with:
          firebaseToolsVersion: 13.35.1
          ...
```

**Comment by nvzoll** [comment]
@redian that's exactly what we did, thanks

**Comment by taeold** [comment]
We've released a new version with a fix (14.0.1). Sorry for the confusion everyone.

**Comment by nvzoll** [comment]
Thank you! I guess we'll stick to v13 for a week just in case...

**Comment by ph360** [comment]
Already is ready this version   npm install -g firebase-tools@14.0.1

**Comment by fivecar** [comment]
@taeold : I still get this on 14.0.1, as recent as an hour ago running `npx firebase-tools deploy --token "$FIREBASE_TOKEN" --project MY-PROJ --only functions` in a GitHub action on the server. Are there potentially still cases where 14.0.1 still fails in this way?

**Comment by ph360** [comment]
> [@taeold](https://github.com/taeold) : I still get this on 14.0.1, as recent as an hour ago running `npx firebase-tools deploy --token "$FIREBASE_TOKEN" --project MY-PROJ --only functions` in a GitHub action on the server. Are there potentially still cases where 14.0.1 still fails in this way?

![Image](https://github.com/user-attachments/assets/77300195-3253-4e05-99ee-a365dfa2cc84)

in github all ok with version 14.0.1

**Comment by fivecar** [comment]
FWIW, 14.0.1 still not ok in my case.
<img width="1128" alt="Image" src="https://github.com/user-attachments/assets/7413a263-5793-486a-9502-a1ac2f36fd94" />

<img width="1031" alt="Image" src="https://github.com/user-attachments/assets/0fc7b1d1-b10c-4ad6-96ce-212dd3ec6c73" />

**Comment by ph360** [comment]
> FWIW, 14.0.1 still not ok in my case. <img alt="Image" width="1128" src="https://private-user-images.githubusercontent.com/39933441/428247202-7413a263-5793-486a-9502-a1ac2f36fd94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMyMTY3MjgsIm5iZiI6MTc0MzIxNjQyOCwicGF0aCI6Ii8zOTkzMzQ0MS80MjgyNDcyMDItNzQxM2EyNjMtNTc5My00ODZhLTk1MDItYTFhYzJmMzZmZDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI5VDAyNDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NDMzYjExZGU3N2NlYjA1ZWFmMmY0YWVkNjdlNGJlNGY0NGJiMzU2M2E1ZDA4NTAxYzM3Y2FjYjVhMGFjOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YuvpojqFLV0xlt0296HZuNU5IKVKhIrNoDCsRB0OMP0">
> 
> <img alt="Image" width="1031" src="https://private-user-images.githubusercontent.com/39933441/428247229-0fc7b1d1-b10c-4ad6-96ce-212dd3ec6c73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMyMTY3MjgsIm5iZiI6MTc0MzIxNjQyOCwicGF0aCI6Ii8zOTkzMzQ0MS80MjgyNDcyMjktMGZjN2IxZDEtYjEwYy00YWQ2LTk2Y2UtMjEyZGQzZWM2YzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI5VDAyNDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YzY0MTcxZDU0MWQxOGE1ODdmZGE3YTYzNjk1MzAzY2M2ZWM0YjQ3ZDdiNGI2YTQ1OWE5MWMzM2QzYmI3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dHiUnFOSA9861gUCMVAyeR3FSIww3UvXMJvWfJKBhc0">

![Image](https://github.com/user-attachments/assets/770f6ffc-161f-4f09-aeb5-99fb066e260b)

**Comment by ph360** [comment]
> > FWIW, 14.0.1 still not ok in my case. <img alt="Image" width="1128" src="https://private-user-images.githubusercontent.com/39933441/428247202-7413a263-5793-486a-9502-a1ac2f36fd94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMyMTY3MjgsIm5iZiI6MTc0MzIxNjQyOCwicGF0aCI6Ii8zOTkzMzQ0MS80MjgyNDcyMDItNzQxM2EyNjMtNTc5My00ODZhLTk1MDItYTFhYzJmMzZmZDk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI5VDAyNDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NDMzYjExZGU3N2NlYjA1ZWFmMmY0YWVkNjdlNGJlNGY0NGJiMzU2M2E1ZDA4NTAxYzM3Y2FjYjVhMGFjOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YuvpojqFLV0xlt0296HZuNU5IKVKhIrNoDCsRB0OMP0">
> > <img alt="Image" width="1031" src="https://private-user-images.githubusercontent.com/39933441/428247229-0fc7b1d1-b10c-4ad6-96ce-212dd3ec6c73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMyMTY3MjgsIm5iZiI6MTc0MzIxNjQyOCwicGF0aCI6Ii8zOTkzMzQ0MS80MjgyNDcyMjktMGZjN2IxZDEtYjEwYy00YWQ2LTk2Y2UtMjEyZGQzZWM2YzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI5VDAyNDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YzY0MTcxZDU0MWQxOGE1ODdmZGE3YTYzNjk1MzAzY2M2ZWM0YjQ3ZDdiNGI2YTQ1OWE5MWMzM2QzYmI3OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dHiUnFOSA9861gUCMVAyeR3FSIww3UvXMJvWfJKBhc0">
> 
> ![Image](https://github.com/user-attachments/assets/770f6ffc-161f-4f09-aeb5-99fb066e260b)

I believe that message is for other reason.   I see that see the policy

**Comment by vamshiOmniWorks** [comment]
This worked for me

- uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.xxx }}"
          channelId: live
          projectId: xxx
          expires: 30d
          firebaseToolsVersion: 13.35.1

**Comment by nilsreichardt** [comment]
I am using Firebase CLI v14.1.0 and still get the error.

Here you see that I'm using v14.1.0

![Image](https://github.com/user-attachments/assets/9209933b-4194-4095-bc0f-ed2326f5ad7e)

Error:

![Image](https://github.com/user-attachments/assets/c7d45627-bd10-473e-9bee-e9a9e76c4e4a)

Logs: https://github.com/SharezoneApp/sharezone-app/actions/runs/14430710787/job/40465822063?pr=1849

**Comment by steveoh** [comment]
This is not working on 14.2.1 which was released today and this issue should be reopened. 

> Error: Functions successfully deployed but could not set up cleanup policy in location us-central1. Pass the --force option to automatically set up a cleanup policy or run 'firebase functions:artifacts:setpolicy' to manually set up a cleanup policy.

If I run that command it shows me

> $ firebase functions:artifacts:setpolicy
> i  A cleanup policy already exists that deletes images older than 1 days.
> i  No changes needed.

So something is not working properly in 14.
